
/* ************************************************************************* */
/*
 *	ppp.c
 *
 *	(C) 1994 - 2006 VOCAL Technologies, Ltd.
 *
 *	ALL RIGHTS RESERVED.  PROPRIETARY AND CONFIDENTIAL.
 *
 *	VOCAL Technologies, Ltd.
 *	90A John Muir Drive.
 *	Buffalo, NY  14228
 *
 *	Product:	LANsEND
 *
 *	Module:		WAN
 *
 *	This file contains the main PPP functions.
 *
 *	Revision Number:	$Revision$
 *	Revision Status:	$State$
 *	Last Modified:		$Date$
 *	Identification:		$Id$
 *
 *	Revision History:	$Log$
 *	Revision History:	Revision 1.1.24.1  2009/04/28 20:56:09  zhangn1
 *	Revision History:	SCR #173564. 2490H Vocal upgrade to Rev 4.56C
 *	Revision History:	
 *
 */
/* ************************************************************************* */

#include "system/system.h"
#include "lansend/global.h"

#include "net/net.h"
#include "sys/sys.h"
#include "dev/dev.h"

#include "dev/devmdm.h"

#include "ip/ip.h"

#include "wan/local.h"

#include "trace/trace.h"

/* ************************************************************************* */

/*
 * FCS lookup table as generated by fcsgen.c
 */
static uint16 far fcstab[256] = {
    0x0000, 0x1189, 0x2312, 0x329b, 0x4624, 0x57ad, 0x6536, 0x74bf,
    0x8c48, 0x9dc1, 0xaf5a, 0xbed3, 0xca6c, 0xdbe5, 0xe97e, 0xf8f7,
    0x1081, 0x0108, 0x3393, 0x221a, 0x56a5, 0x472c, 0x75b7, 0x643e,
    0x9cc9, 0x8d40, 0xbfdb, 0xae52, 0xdaed, 0xcb64, 0xf9ff, 0xe876,
    0x2102, 0x308b, 0x0210, 0x1399, 0x6726, 0x76af, 0x4434, 0x55bd,
    0xad4a, 0xbcc3, 0x8e58, 0x9fd1, 0xeb6e, 0xfae7, 0xc87c, 0xd9f5,
    0x3183, 0x200a, 0x1291, 0x0318, 0x77a7, 0x662e, 0x54b5, 0x453c,
    0xbdcb, 0xac42, 0x9ed9, 0x8f50, 0xfbef, 0xea66, 0xd8fd, 0xc974,
    0x4204, 0x538d, 0x6116, 0x709f, 0x0420, 0x15a9, 0x2732, 0x36bb,
    0xce4c, 0xdfc5, 0xed5e, 0xfcd7, 0x8868, 0x99e1, 0xab7a, 0xbaf3,
    0x5285, 0x430c, 0x7197, 0x601e, 0x14a1, 0x0528, 0x37b3, 0x263a,
    0xdecd, 0xcf44, 0xfddf, 0xec56, 0x98e9, 0x8960, 0xbbfb, 0xaa72,
    0x6306, 0x728f, 0x4014, 0x519d, 0x2522, 0x34ab, 0x0630, 0x17b9,
    0xef4e, 0xfec7, 0xcc5c, 0xddd5, 0xa96a, 0xb8e3, 0x8a78, 0x9bf1,
    0x7387, 0x620e, 0x5095, 0x411c, 0x35a3, 0x242a, 0x16b1, 0x0738,
    0xffcf, 0xee46, 0xdcdd, 0xcd54, 0xb9eb, 0xa862, 0x9af9, 0x8b70,
    0x8408, 0x9581, 0xa71a, 0xb693, 0xc22c, 0xd3a5, 0xe13e, 0xf0b7,
    0x0840, 0x19c9, 0x2b52, 0x3adb, 0x4e64, 0x5fed, 0x6d76, 0x7cff,
    0x9489, 0x8500, 0xb79b, 0xa612, 0xd2ad, 0xc324, 0xf1bf, 0xe036,
    0x18c1, 0x0948, 0x3bd3, 0x2a5a, 0x5ee5, 0x4f6c, 0x7df7, 0x6c7e,
    0xa50a, 0xb483, 0x8618, 0x9791, 0xe32e, 0xf2a7, 0xc03c, 0xd1b5,
	0x2942, 0x38cb, 0x0a50, 0x1bd9, 0x6f66, 0x7eef, 0x4c74, 0x5dfd,
    0xb58b, 0xa402, 0x9699, 0x8710, 0xf3af, 0xe226, 0xd0bd, 0xc134,
    0x39c3, 0x284a, 0x1ad1, 0x0b58, 0x7fe7, 0x6e6e, 0x5cf5, 0x4d7c,
    0xc60c, 0xd785, 0xe51e, 0xf497, 0x8028, 0x91a1, 0xa33a, 0xb2b3,
    0x4a44, 0x5bcd, 0x6956, 0x78df, 0x0c60, 0x1de9, 0x2f72, 0x3efb,
    0xd68d, 0xc704, 0xf59f, 0xe416, 0x90a9, 0x8120, 0xb3bb, 0xa232,
    0x5ac5, 0x4b4c, 0x79d7, 0x685e, 0x1ce1, 0x0d68, 0x3ff3, 0x2e7a,
    0xe70e, 0xf687, 0xc41c, 0xd595, 0xa12a, 0xb0a3, 0x8238, 0x93b1,
    0x6b46, 0x7acf, 0x4854, 0x59dd, 0x2d62, 0x3ceb, 0x0e70, 0x1ff9,
    0xf78f, 0xe606, 0xd49d, 0xc514, 0xb1ab, 0xa022, 0x92b9, 0x8330,
    0x7bc7, 0x6a4e, 0x58d5, 0x495c, 0x3de3, 0x2c6a, 0x1ef1, 0x0f78
};

#define pppfcs(fcs, c)		(((fcs >> 8) & 0x00ff) ^ fcstab[(fcs ^ (c & 0x00ff)) & 0x00ff])

#define SP_CHAR 		0x20

/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */

/* ************************************************************************* */

/* General trace routine */
MODULE void
ppp_log (struct ppp_s *ppp_p, char *comment)
{
	if (ppp_p->iface->trace & PPP_DEBUG_PACKET)
		trace_log(ppp_p->iface,"PPP %s",comment);
}

/* ************************************************************************* */

/* Bad packet */
MODULE void
ppp_error (struct ppp_s *ppp_p, struct mbuf *bp, char *comment)
{
	free_p(bp);
	PPP_LOG(ppp_p, comment);
}

/* ************************************************************************* */

/* Unknown type input packet */
MODULE void
ppp_skipped (struct ppp_s *ppp_p, struct mbuf *bp, char *comment)
{
	struct ipcp_pdv_s *ipcp_p;

	if ((ipcp_p = ppp_p->fsm[IPcp].pdv) != NULL) {
		slhc_toss(ipcp_p->slhcp);
	}
	PPP_ERROR(ppp_p, bp, "PPP Skipped");
}

/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */
/* ************************************************************************* */

/* ************************************************************************* */

/* Put a packet on output queue */
ENTRY int
ppp_send (struct iface *ifp, struct mbuf *bp, void *unused)
{
	struct ppp_s *ppp_p;
	int ret;

	if (ifp == NULLIF
	 || (ppp_p = (struct ppp_s *) ifp->pppedv) == NULL) {
		free_p(bp);
		return -1;
	}

	/* Count outgoing packets */
	ifp->ifOutUcastPkts++;

	if (ppp_p->phase == pppDEAD) {
		PPP_ERROR(ppp_p, bp, "line not up");
		ifp->ifOutDiscards++;
		return -1;
	}

	switch (bp->b_type) {
	case PT_IP:
		if (ppp_p->fsm[IPcp].state != fsmOPENED) {
			PPP_ERROR(ppp_p, bp, "not open for IP traffic");
			ifp->ifOutDiscards++;
			return -1;
		}
		break;

	case PPP_IPCP_PROTOCOL:
	case PPP_LCP_PROTOCOL:
	case PPP_PAP_PROTOCOL:
	case PPP_CHAP_PROTOCOL:
		break;

	default:
		trace_log(ifp, "PPP Unknown packet protocol: %x;",
			bp->b_type);
		ifp->ifOutErrors++;
		free_p(bp);
		return -1;
	};
	ret = if_send(ifp,bp,NULL);
	return ret;
}

/****************************************************************************/
/* Packetize PPP output for asynchronous or synchronous device */
/* (process started by ppp_init) */
/*
 * This can now be killed by an alert -1.
 * NOTE: This MUST be an interface transmit task, ie ifp->txproc == if_tx.
 *	 ifp->txproc == NULLPROC is a terminate condition.
 */
ENTRY void
ppp_out (int dev, void *p1, void *p2)
{
	struct iface *ifp = (struct iface *) p1;
	struct ppp_s *ppp_p = (struct ppp_s *) ifp->pppedv;

	struct mbuf *bp;
	struct mbuf *head_bp = NULLBUF; /* first buffer */
	struct mbuf *tail_bp = NULLBUF; /* current buffer */
	register char *cp;
	register int c;
	uint16 cnt, size, octets;

	/* Clear out the output queue upon entry.  This keeps packets that
	 * were queued up by DECIDE from going out without being checked
	 * by PPP_SEND. */
	while (ifp->outq != NULLBUF) {
		free_p(dequeue(&ifp->outq));
		ifp->outdepth++;
	}

	do {
		uint16 protocol;
		negotiate_t negotiated;
		int full_lcp, full_ac, full_p;
		int len = PPP_HDR_LEN;
		uint32 accm = LCP_ACCM_DEFAULT;
		uint16 calc_fcs = HDLC_FCS_START;

		while (ifp->outq == NULLBUF && ifp->txproc != NULLPROC) {
			if (pwait(&ifp->outq) != 0) {
				ifp->txproc = NULLPROC;
				killself();
			}
		}

		/* Process was killed. */
		if (ifp->txproc == NULLPROC)
			continue;

		/* Process the output packet */
		bp = dequeue(&ifp->outq);
		ifp->outdepth++;

		negotiated = ppp_p->fsm[Lcp].remote.work;

		switch (protocol = bp->b_type) {
		case PT_IP:
			protocol = PPP_IP_PROTOCOL;

			if (ppp_p->fsm[IPcp].remote.work & IPCP_N_COMPRESS) {
				register struct ipcp_pdv_s *ipcp_p =
					ppp_p->fsm[IPcp].pdv;
				register struct ipcp_value_s *vp =
					ppp_p->fsm[IPcp].remote.work_pdv;

				/* Attempt TCP/IP header compression */
				switch (slhc_compress(ipcp_p->slhcp, &bp, vp->slot_compress)) {
				case SL_TYPE_IP:
					protocol = PPP_IP_PROTOCOL;
					break;
				case SL_TYPE_COMPRESSED_TCP:
					protocol = PPP_VJCH_PROTOCOL;
					break;
				case SL_TYPE_UNCOMPRESSED_TCP:
					protocol = PPP_VJUCH_PROTOCOL;
					break;
				default:
					PPP_ERROR(ppp_p, bp, "bad IP packet");
					ifp->ifOutErrors++;
					continue;
				};
			}
			break;

		default:
			break;
		};

		if ((full_lcp = (protocol == PPP_LCP_PROTOCOL)) == 0
		  && negotiated & LCP_N_ACCM) {
			register struct lcp_value_s *vp =
				(struct lcp_value_s *) ppp_p->fsm[Lcp].remote.work_pdv;
			accm = vp->accm;
		}

		/* Compress protocol field if allowed */
		if ((full_p = (full_lcp
				||  !(negotiated & LCP_N_PFC)
				||  protocol >= 0x00ff))
			== FALSE) {
			--len;
		}

		/* Discard HDLC address and control fields if possible */
		if ((full_ac = (full_lcp
				||  !(negotiated & LCP_N_ACFC)))
			== FALSE) {
			len -= 2;
		}

		/* Load header with proper values */
		pushdown(&bp,len);
		cp = bp->data;

		if (full_ac) {
			*cp++ = HDLC_ALL_ADDR;
			*cp++ = HDLC_UI;
		}
		if (full_p)
			*cp++ = (protocol >> 8) & 0xff;
		*cp++ = (protocol & 0x00ff);

		dump(ifp,IF_TRACE_OUT,bp);

		octets = len_p (bp);

		switch (ifp->d_type) {
		/* Process byte escaping for octect oriented devices */
		case IFD_MDM:
		case IFD_ASYNC:
			octets += 3; 	/* count FCS and final flag */

			/* Build a series of buffers for the raw packet.
			 */
			if ((tail_bp = alloc_ibuf(MXU_DEFAULT, -IBUF_HEADER)) == NULLBUF) {
				PPP_ERROR(ppp_p, bp, (char *) Nospace);
				ifp->ifOutDiscards++;
				continue;
			}
			tail_bp->flags |= MBUF_ETHERNET;
			cnt = 0;
			cp = tail_bp->data;
			size = MBUF_POST(tail_bp);

			/* No need to send an opening flag if the previous
			 * packet is still being transmitted.
			 */
			if (ifp->d_type == IFD_MDM) {
				if (Mdm[ifp->dev]->txbp == NULLBUF)
				{
					/* Flush out any line garbage */
					*cp++ = HDLC_FLAG;
					cnt++;
					ppp_p->OutOpenFlag++;
				}
			}

			/* Copy input to output, escaping special characters */
			while ((c = PULLCHAR(&bp)) != -1) {
				c &= 0x00ff;
				if (cnt + 7 > size) {
					/* not enough room for escaped byte,
					 * plus frame end.
					 */
					tail_bp->cnt = cnt;
					append(&head_bp, tail_bp);

					if ((tail_bp = alloc_ibuf(MXU_DEFAULT, -IBUF_HEADER)) == NULLBUF) {
						free_p(head_bp);
						head_bp = NULLBUF;
						PPP_ERROR(ppp_p, bp, (char *) Nospace);
						ifp->ifOutDiscards++;
						break;
					}
					tail_bp->flags |= MBUF_ETHERNET;
					cnt = 0;
					cp = tail_bp->data;
					size = MBUF_POST(tail_bp);
				}

				/* Let other processes have a chance to run if required */
				if ((cnt % 128) == 0)
					pwait (NULL);

				/* Fold char value into FCS calculated so far */
				calc_fcs = pppfcs(calc_fcs, c);

				if (((c < SP_CHAR) && (accm & (1L << c)))
					|| (c == HDLC_ESC_ASYNC)
					|| (c == HDLC_FLAG)) {
					*cp++ = HDLC_ESC_ASYNC;
					*cp++ = (c ^ HDLC_ESC_COMPL);
					cnt += 2;
				} else {
					*cp++ = c;
					cnt++;
				}
			}

			if (head_bp == NULLBUF  &&  tail_bp == NULLBUF) {
				/* out of memory */
				continue;
			}

			/* Final FCS calculation */
			calc_fcs ^= 0xffff;		/* complement */
			c = (calc_fcs & 0x00ff);	/* Least significant byte first */
			if (((c < SP_CHAR) && (accm & (1L << c)))
				 ||(c == HDLC_ESC_ASYNC)
				 ||(c == HDLC_FLAG)) {
				*cp++ = HDLC_ESC_ASYNC;
				*cp++ = (c ^ HDLC_ESC_COMPL);
				cnt += 2;
			} else {
				*cp++ = c;
				cnt++;
			}
			c = (calc_fcs >> 8) & 0xff;		/* Most significant byte next */
			if (((c < SP_CHAR) && (accm & (1L << c)))
				 ||(c == HDLC_ESC_ASYNC)
				 ||(c == HDLC_FLAG)) {
				*cp++ = HDLC_ESC_ASYNC;
				*cp++ = (c ^ HDLC_ESC_COMPL);
				cnt += 2;
			} else {
				*cp++ = c;
				cnt++;
			}

			/* Tie off the packet */
			*cp++ = HDLC_FLAG;
			tail_bp->cnt = ++cnt;
			append(&head_bp, tail_bp);
			break;
		/* No escaping necessary for synchronous bit oriented devices */
		case IFD_SYNC:
			head_bp = bp;
			break;
		default:;
		}

		if (ifp->trace & IF_TRACE_RAW)
			raw_dump(ifp,IF_TRACE_OUT,head_bp);

		/* Accumulate the number of octets being sent */
		ifp->ifOutOctets += octets;
		ifp->rawsndcnt++;
		ifp->lastsent = secclock();

		if ((*ifp->iosend)(ifp,head_bp) == -1) {
			ifp->txproc = NULLPROC;
		} else {
			head_bp = NULLBUF;
		}
	} while (ifp->txproc != NULLPROC);
}

/****************************************************************************/

/* Packetize PPP input from asynchronous device */
/* (process started by ppp_init) */
ENTRY void
ppp_asy_in (int dev, void *p1, void *p2)
{
	struct iface *ifp = (struct iface *) p1;
	struct ppp_s *ppp_p = (struct ppp_s *) ifp->pppedv;
	uint32 accm = LCP_ACCM_DEFAULT;
	uint16 calc_fcs = HDLC_FCS_START;
	struct mbuf *raw_bp = NULLBUF;
	register struct mbuf *head_bp = NULLBUF;
	char *cp;			/* next byte in mbuf */
	uint16 size;
	register int c;
#define MODE_TOSS	0x01
#define MODE_ESCAPED	0x02
	int mode = MODE_TOSS;

	while ((c = (*ifp->ioget)(ifp)) != -1) {
		c &= 0x00ff;

		if (raw_bp != NULLBUF	&&  raw_bp->cnt < raw_bp->size) {
			raw_bp->data[raw_bp->cnt++] = c;
		}

		if (c == HDLC_FLAG) {
			if (raw_bp != NULLBUF) {
				if (raw_bp->cnt > 1) {
					raw_dump(ifp, IF_TRACE_IN, raw_bp);
				}
				if (ifp->trace & IF_TRACE_RAW) {
					raw_bp->cnt = 0;
				} else {
					free_p(raw_bp);
					raw_bp = NULLBUF;
				}
			} else if (ifp->trace & IF_TRACE_RAW) {
				raw_bp = alloc_mbuf(2 * (LCP_MRU_HI
							+ HDLC_ENVLEN
							+ PPP_PADDING));
			}

			if (mode & MODE_ESCAPED) {
				PPP_SKIPPED(ppp_p, head_bp,
					"deliberate cancellation");
				ifp->ifInDiscards++;
			} else if (mode & MODE_TOSS) {
				free_p(head_bp);
			} else if (head_bp != NULLBUF) {
				if (calc_fcs != HDLC_FCS_FINAL) {
					PPP_SKIPPED(ppp_p, head_bp,
						"checksum error");
					ppp_p->InChecksum++;
					ifp->ifInErrors++;
				} else {
					/* trim off FCS bytes */
					head_bp->cnt -= 2;
					net_route(ifp, head_bp);
				}
			} else {
				ppp_p->InOpenFlag++;
			}

			/* setup for next buffer */
			head_bp = NULLBUF;
			accm = LCP_ACCM_DEFAULT;
			calc_fcs = HDLC_FCS_START;
			mode = FALSE;
			continue;
		}

		/* We reach here for every byte inside a frame.
		 * (The order of the following tests is important.)
		 * Discard spurious control characters.
		 * Check for escape sequence.
		 * (Allow escaped escape.)
		 */
		if (c < SP_CHAR && (accm & (1L << c))) {
			continue;
		} else if (mode & MODE_ESCAPED) {
			mode &= ~MODE_ESCAPED;
			c ^= HDLC_ESC_COMPL;
		} else if (c == HDLC_ESC_ASYNC) {
			mode |= MODE_ESCAPED;
			continue;
		}

		/* We reach here with a byte for the buffer.
		 * Make sure there is room for it.
		 */
		if (head_bp == NULLBUF) {
			if (mode & MODE_TOSS) {
				continue;
			}
			size = ifp->mru + HDLC_ENVLEN + PPP_PADDING;
			if ((head_bp = alloc_ibuf(size, -PPP_HDR_LEN)) == NULLBUF) {
				PPP_SKIPPED(ppp_p, head_bp, (char *) Nospace);
				ifp->ifInDiscards++;
				mode |= MODE_TOSS;
				continue;
			}
			head_bp->flags |= MBUF_ETHERNET;
			size = MBUF_POST(head_bp);
			cp = head_bp->data;
			head_bp->cnt = 0;

			/* Use negotiated values if LCP finished */
			if (ppp_p->fsm[Lcp].state == fsmOPENED) {
				if (ppp_p->fsm[Lcp].local.work & LCP_N_ACCM) {
					register struct lcp_value_s *vp =
						(struct lcp_value_s *) ppp_p->fsm[Lcp].local.work_pdv;
					accm = vp->accm;
				}
			}
		} else if (head_bp->cnt >= size) {
			/* too much data */
			PPP_SKIPPED(ppp_p, head_bp, "MRU exceeded");
			ifp->ifInErrors++;
			head_bp = NULLBUF;
			mode |= MODE_TOSS;
			continue;
		}

		/* Store the byte, increment counts */
		*cp++ = c;
		head_bp->cnt++;
		calc_fcs = pppfcs(calc_fcs, c);
	}

	/* clean up afterward */
	free_p(raw_bp);
	free_p(head_bp);
	ifp->rxproc = NULLPROC;
}

/* Process incoming PPP packets */
/* (called from network task) */
ENTRY void
ppp_proc (struct iface *ifp, struct mbuf *bp)
{
	struct ppp_s *ppp_p;
	uint16 protocol;
	negotiate_t negotiated = FALSE;
	uint16 size;

	if (ifp == NULLIF) {
		return;
	}
	if (bp == NULLBUF) {
		trace_log(ifp, "ppp_proc: missing buffer");
		return;
	}
	ppp_p = (struct ppp_s *) ifp->pppedv;
	size = len_p (bp);

	if ((ifp->d_type == IFD_ASYNC) || (ifp->d_type == IFD_MDM))
		size += 3;		/* count FCS and final flag */
	ifp->ifInOctets += size;

	/* Use negotiated values if LCP finished */
	if (ppp_p->fsm[Lcp].state == fsmOPENED) {
		negotiated = ppp_p->fsm[Lcp].local.work;
	}

	/* HDLC address and control fields may be compressed out */
	if ((uint8)bp->data[0] != HDLC_ALL_ADDR) {
		if (!(negotiated & LCP_N_ACFC)) {
			PPP_SKIPPED(ppp_p, bp, "missing ALL address");
			ppp_p->InFrame++;
			ifp->ifInErrors++;
			return;
		}
	} else if ((uint8)bp->data[1] != HDLC_UI) {
		if (!(negotiated & LCP_N_ACFC)
		 || !(negotiated & LCP_N_PFC)) {
			PPP_SKIPPED(ppp_p, bp, "missing UI");
			ppp_p->InFrame++;
			ifp->ifInErrors++;
			return;
		}
	} else {
		/* skip address/control fields */
		pull16(&bp);
	}

	/* Initialize the expected header */
	protocol = PULLCHAR(&bp);

	/* First byte of PPP protocol field may be compressed out */
	if (protocol & 0x01) {
		if (!(negotiated & LCP_N_PFC)) {
			PPP_SKIPPED(ppp_p, bp, "missing upper protocol byte");
			ppp_p->InFrame++;
			ifp->ifInErrors++;
			return;
		}
	} else {
		protocol = (protocol << 8) | PULLCHAR(&bp);

		/* Second byte of PPP protocol field must be odd */
		if (!(protocol & 0x01)) {
			PPP_SKIPPED(ppp_p, bp, "missing lower protocol byte");
			ppp_p->InFrame++;
			ifp->ifInErrors++;
			return;
		}
	}

	ppp_packet_proc (ifp, bp, size, protocol);
}

/* ************************************************************************* */

/* Common code used by PPP and PPPoE */

ENTRY void
ppp_packet_proc (struct iface *ifp, struct mbuf *bp, uint16 size, uint16 protocol)
{
	struct ppp_s *ppp_p = (struct ppp_s *) ifp->pppedv;
	struct ipcp_pdv_s *ipcp_p;

	switch (protocol) {
	case PPP_IPCP_PROTOCOL: /* IP Control Protocol */
		if (ppp_p->phase != pppNETWORK) {
			PPP_ERROR(ppp_p, bp, "not ready for IPCP traffic");
			ifp->ifInDiscards++;
			break;
		}
		ppp_p->InGoodOctets += size;
		ifp->ifInUcastPkts++;
		ppp_p->InNCP[IPcp]++;
		fsm_proc(&(ppp_p->fsm[IPcp]),bp);
		break;

	case PPP_IP_PROTOCOL:	/* Regular IP */
		if (ppp_p->fsm[IPcp].state != fsmOPENED) {
			PPP_ERROR(ppp_p, bp, "not open for IP traffic");
			ifp->ifInDiscards++;
			break;
		}
		ppp_p->InGoodOctets += size;
		ifp->ifInUcastPkts++;
		bp->b_type = PT_IP;
		ip_route(ifp,bp,0);
		break;

	case PPP_VJCH_PROTOCOL: 	/* Van Jacobson Compressed TCP/IP */
		if (ppp_p->fsm[IPcp].state != fsmOPENED) {
			PPP_SKIPPED(ppp_p, bp, "not open for Compressed TCP/IP traffic");
			ifp->ifInDiscards++;
			break;
		}

		if (!(ppp_p->fsm[IPcp].local.work & IPCP_N_COMPRESS)) {
			PPP_SKIPPED(ppp_p, bp, "Compressed TCP/IP not enabled");
			ifp->ifInDiscards++;
			break;
		}

		ipcp_p = ppp_p->fsm[IPcp].pdv;
		if (slhc_uncompress(ipcp_p->slhcp, &bp) <= 0) {
			PPP_ERROR(ppp_p, bp, "Compressed TCP/IP packet error");
			ifp->ifInErrors++;
			break;
		}
		ppp_p->InGoodOctets += size;
		ifp->ifInUcastPkts++;
		bp->b_type = PT_IP;
		ip_route(ifp,bp,0);
		break;

	case PPP_VJUCH_PROTOCOL:	/* Van Jacobson Uncompressed TCP/IP */
		if (ppp_p->fsm[IPcp].state != fsmOPENED) {
			PPP_SKIPPED(ppp_p, bp, "not open for Uncompressed TCP/IP traffic");
			ifp->ifInDiscards++;
			break;
		}

		if (!(ppp_p->fsm[IPcp].local.work & IPCP_N_COMPRESS)) {
			PPP_SKIPPED(ppp_p, bp, "Uncompressed TCP/IP not enabled");
			ifp->ifInDiscards++;
			break;
		}

		ipcp_p = ppp_p->fsm[IPcp].pdv;
		if (slhc_remember(ipcp_p->slhcp, &bp) <= 0) {
			PPP_ERROR(ppp_p, bp, "Uncompressed TCP/IP packet error");
			ifp->ifInErrors++;
			break;
		}
		ppp_p->InGoodOctets += size;
		ifp->ifInUcastPkts++;
		bp->b_type = PT_IP;
		ip_route(ifp,bp,0);
		break;

	case PPP_LCP_PROTOCOL:	/* Link Control Protocol */
		ppp_p->InGoodOctets += size;
		ifp->ifInUcastPkts++;
		ppp_p->InNCP[Lcp]++;
		fsm_proc(&(ppp_p->fsm[Lcp]),bp);
		break;

	case PPP_PAP_PROTOCOL:	/* Password Authenticate Protocol */
		if (ppp_p->phase != pppAUTHENTICATE
		 && ppp_p->phase != pppNETWORK) {
			PPP_ERROR(ppp_p, bp, "not ready for Authentication");
			ifp->ifInDiscards++;
			break;
		}
		ppp_p->InGoodOctets += size;
		ifp->ifInUcastPkts++;
		ppp_p->InNCP[Pap]++;
		pap_proc(&(ppp_p->fsm[Pap]),bp);
		break;

	case PPP_CHAP_PROTOCOL:  /* Challenge Handshake Authenticate Protocol */
		if (ppp_p->phase != pppAUTHENTICATE
		 && ppp_p->phase != pppNETWORK) {
			PPP_ERROR(ppp_p, bp, "not ready for Authentication");
			ifp->ifInDiscards++;
			break;
		}
		ppp_p->InGoodOctets += size;
		ifp->ifInUcastPkts++;
		ppp_p->InNCP[CHap]++;
		chap_proc(&(ppp_p->fsm[CHap]),bp);
		break;

	default:

		trace_log(ifp, "PPP Unknown protocol field: %x;",
			protocol);

		ppp_p->InUnknown++;
		ifp->ifInErrors++;

		/* Build Protocol Reject packet,
		 * and send it as an LCP packet.
		 */
		pushdown(&bp, sizeof(protocol));
		put16(bp->data,protocol);
		fsm_send(&(ppp_p->fsm[Lcp]), PROT_REJ, 0, bp);
		break;
	};
}

/************************************************************************/

/* Keep track of changes in I-O status */
/* (called through iftype iostatus vector) */
ENTRY void
ppp_iostatus (struct iface *ifp, int command, sint31 value)
{
	struct ppp_s *ppp_p = (struct ppp_s *) ifp->pppedv;

	switch (command) {
	case PARAM_UP:
		PPP_LOG(ppp_p, "Physical layer up");
		fsm_up(&(ppp_p->fsm[Lcp]));
		return;

	case PARAM_DOWN:
		PPP_LOG(ppp_p, "Physical layer down");

		fsm_down(&(ppp_p->fsm[Lcp]));
		ppp_p->phase = pppDEAD;
		return;
	};
	return;
}

ENTRY int
ppp_discard (struct iface *ifp, struct mbuf *bp)
{
	struct ppp_s *ppp_p = (struct ppp_s *) ifp->pppedv;
	int ret;

	ret = fsm_send(&(ppp_p->fsm[Lcp]), DISCARD_REQ, 0, bp);
	return ret;
}

ENTRY int
ppp_echo (struct iface *ifp, struct mbuf *bp)
{
	struct ppp_s *ppp_p = (struct ppp_s *) ifp->pppedv;
	int ret;

	ret = fsm_send(&(ppp_p->fsm[Lcp]), ECHO_REQ, 0, bp);
	return ret;
}

/****************************************************************************/

/* Attach PPP control structures for a Point-to-Point interface. */
/* (Called indirectly by setencap and by processing PPP commands.) */
ENTRY void
ppp_attach (struct iface *ifp)
{
	register struct ppp_s *ppp_p;

	if (ifp->pppedv == NULL) {
		ifp->pppedv = ppp_p = (struct ppp_s *) callocw(1,sizeof(struct ppp_s));
		ppp_p->phase = pppDEAD;

		ppp_p->iface = ifp;

		lcp_attach(ppp_p);
		pap_attach(ppp_p);
		chap_attach(ppp_p);
		ipcp_attach(ppp_p);
	}
	doppp_quick (0, NULL, (void *) ifp);
}

/* Detach encapsulation structures. */
ENTRY void
ppp_detach (struct iface *ifp)
{
	struct ppp_s *ppp_p = (struct ppp_s *) ifp->pppedv;
	int fsmi;

	ppp_suspend (ifp);

	for (fsmi = Lcp; fsmi < fsmi_Size;) {
		fsm_free(&(ppp_p->fsm[fsmi++]));
	}
	free(ppp_p->peername);
	free(ppp_p);
	ifp->pppedv = NULL;
}

/* Process to force a connection to go down.
 *
 * IFP is the interface to bring down. */
ENTRY void
ppp_timeout (struct iface *ifp)
{
	struct ppp_s *ppp_p = (struct ppp_s *) ifp->pppedv;

	fsm_close(&(ppp_p->fsm[Lcp]));	/* Administratively close link */
}

/* Start PPP processes for a Point-to-Point interface. */
/* (Called from setencap.) */
ENTRY int
ppp_start (struct iface *ifp)
{
	struct ppp_s *ppp_p;
	char *ifn;

	if (ifp->pppedv == NULL)
		ppp_attach (ifp);

	ppp_p = (struct ppp_s *) ifp->pppedv;
	ppp_p->phase = pppDEAD;

	lcp_init(ppp_p);		/* Sets default MTU to be used by PPP */
	pap_init(ppp_p);
	chap_init(ppp_p);
	ipcp_init(ppp_p);

	switch (ifp->d_type) {
	case IFD_MDM:
	case IFD_ASYNC:
		if (ifp->ioctl != NULL) {
			ifp->ioctl (ifp, PARAM_TRIG, TRUE, HDLC_FLAG);
		}
		ifp->rxproc = newproc(ifn = if_name(ifp, " in"),
				1024, ppp_asy_in, ifp->dev, ifp, NULL, 0);
		free(ifn);
		setpriority (ifp->rxproc, 5);
		/* Note fall through */

	case IFD_SYNC:
		killproc(ifp->txproc);	/* eliminate default */
		ifp->txproc = newproc(ifn = if_name(ifp, " out"),
				1024, ppp_out, ifp->dev, ifp, NULL, 0);
		free(ifn);
		setpriority (ifp->txproc, -5);
		break;

	case IFD_PACKET:
	default:
		break;
	};
	fsm_open (&(ppp_p->fsm[Lcp]));		/* Start control protocols */
	fsm_open (&(ppp_p->fsm[IPcp]));

	if (ifp->ioctl != NULL) {
		/* If carrier is detected, bring up PPP */
		if (ifp->ioctl (ifp, PARAM_DTR, FALSE, 0) && ifp->ioctl (ifp, PARAM_DCD, FALSE, 0)) {
			ppp_iostatus (ifp, PARAM_UP, 0L);
		}
	}
	return 0;
}

/* Suspend PPP operation.  Called by setencap when changing encapsulations. */
ENTRY void
ppp_suspend (struct iface *ifp)
{
	struct ppp_s *ppp_p = (struct ppp_s *) ifp->pppedv;

	if (ppp_p == NULL)
		return;

	fsm_down(&(ppp_p->fsm[Lcp]));	/* Indicate link down condition */
	ppp_p->phase = pppDEAD;

	pwait (NULL);
	free(ppp_p->peername);
	ppp_p->peername = NULL;

	ifp->mtu = MXU_DEFAULT;

	/* Clear the remaining packets in the queue if any */
	while (ifp->outq != NULLBUF) {
		free_p(dequeue(&ifp->outq));
		ifp->outdepth++;
	}
}
