/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT d55.cdb */

#undef CHIP_5510PG2_2

/*  Include Header Files  */
#include <std.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>

#ifdef __cplusplus
extern "C" {
#endif

extern SWI_Obj KNL_swi;
extern SWI_Obj VOCAL_bg_process_swi;
extern SWI_Obj VOCAL_fg_process_swi;
extern TSK_Obj TSK_idle;
extern LOG_Obj LOG_system;
extern void CSL_cfgInit();

#ifdef __cplusplus
}
#endif /* extern "C" */
