/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT PLX.CDB */

/* MODULE PARAMETERS */
GBL_USERINITFXN = _FXN_F_nop;
GBL_BIOS_BOOTFXN = GBL_F_biosbootfxn;

MEM_SEGZERO = SDRAM_3;
MEM_MALLOCSEG = SDRAM_3;

CLK_TIMEFXN = CLK_F_getltime;
CLK_HOOKFXN = CLK_F_run;

PRD_THOOKFXN = KNL_tick_stub;

RTDX_DATAMEMSEG = DARAM;

HST_DSMBUFSEG = DARAM;

SWI_EHOOKFXN = GBL_NULL;
SWI_IHOOKFXN = GBL_NULL;
SWI_EXECFXN = SWI_F_exec;
SWI_RUNFXN = SWI_F_run;

TSK_STACKSEG = SDRAM_3;
TSK_VCREATEFXN = _FXN_F_nop;
TSK_VDELETEFXN = _FXN_F_nop;
TSK_VEXITFXN = _FXN_F_nop;

IDL_CALIBRFXN = GBL_NULL;

SYS_ABORTFXN = _UTL_doAbort;
SYS_ERRORFXN = _UTL_doError;
SYS_EXITFXN = _UTL_halt;
SYS_PUTCFXN = _UTL_doPutc;

GIO_CREATEFXN = _FXN_F_nop;
GIO_DELETEFXN = _FXN_F_nop;
GIO_PENDFXN = _FXN_F_nop;
GIO_POSTFXN = _FXN_F_nop;

PWRM_PWRM_BOOTHOOKFXN = _FXN_F_nop;

/* OBJECT ALIASES */
_DARAM = DARAM;
_VECT = VECT;
_Flash = Flash;
_SDRAM = SDRAM;
_FLASHMIRROR = FLASHMIRROR;
_MAILBOX = MAILBOX;
_SDRAM_1 = SDRAM_1;
_SDRAM_2 = SDRAM_2;
_SDRAM_3 = SDRAM_3;
_SDRAM_4 = SDRAM_4;
_SDRAM_5 = SDRAM_5;
_DARAM_VOC = DARAM_VOC;
_VOC_STORE = VOC_STORE;
_PRD_clock = PRD_clock;
_RTA_fromHost = RTA_fromHost;
_RTA_toHost = RTA_toHost;
_HWI_RESET = HWI_RESET;
_HWI_NMI = HWI_NMI;
_HWI_INT2 = HWI_INT2;
_HWI_INT3 = HWI_INT3;
_HWI_INT4 = HWI_INT4;
_HWI_INT5 = HWI_INT5;
_HWI_INT6 = HWI_INT6;
_HWI_INT7 = HWI_INT7;
_HWI_INT8 = HWI_INT8;
_HWI_INT9 = HWI_INT9;
_HWI_INT10 = HWI_INT10;
_HWI_INT11 = HWI_INT11;
_HWI_INT12 = HWI_INT12;
_HWI_INT13 = HWI_INT13;
_HWI_INT14 = HWI_INT14;
_HWI_INT15 = HWI_INT15;
_HWI_INT16 = HWI_INT16;
_HWI_INT17 = HWI_INT17;
_HWI_INT18 = HWI_INT18;
_HWI_INT19 = HWI_INT19;
_HWI_INT20 = HWI_INT20;
_HWI_INT21 = HWI_INT21;
_HWI_INT22 = HWI_INT22;
_HWI_INT23 = HWI_INT23;
_HWI_BERR = HWI_BERR;
_HWI_DLOG = HWI_DLOG;
_HWI_RTOS = HWI_RTOS;
_HWI_SINT27 = HWI_SINT27;
_HWI_SINT28 = HWI_SINT28;
_HWI_SINT29 = HWI_SINT29;
_HWI_SINT30 = HWI_SINT30;
_HWI_SINT31 = HWI_SINT31;
_KNL_swi = KNL_swi;
_VOCAL_fg_process_swi = VOCAL_fg_process_swi;
_VOCAL_bg_process_swi = VOCAL_bg_process_swi;
_TSK_idle = TSK_idle;
_PLEXUS_idl = PLEXUS_idl;
_LNK_dataPump = LNK_dataPump;
_RTA_dispatcher = RTA_dispatcher;
_IDL_cpuLoad = IDL_cpuLoad;
_LOG_system = LOG_system;
_trace = trace;
_RxPipe = RxPipe;
_IDL_busyObj = IDL_busyObj;

/* MODULE GBL */

SECTIONS {
   .vers block(0x20000) (COPY): {} /* version information */
}

-priority
-llnkrtdx.a55l
-ldrivers.a55l         /* device drivers support */
-lsioboth.a55l         /* supports both SIO models */
-lbiosi.a55l           /* DSP/BIOS support */
-lrtdxx.lib            /* RTDX JTAG support */ 
-lcsl5502x.lib
-lrts55x.lib           /* C and C++ run-time library support */
-lclki.a55l

/* MODULE MEM */
-stack 0x1400
-sysstack 0xc00

SECTIONS { .sysstack : block(0x20000) fill = 0xfeeb {
           GBL_sysstackbeg = .;
           *(.sysstack)
           GBL_sysstackend = GBL_sysstackbeg + 0xc00 -1 ;
            _HWI_SYSSTKTOP = GBL_sysstackbeg; 
            _HWI_SYSSTKBOTTOM =
(GBL_sysstackend+1);
       } > DARAM}

MEMORY {
   DARAM:      origin = 0x600,         len = 0x4a00
   VECT:       origin = 0x500,         len = 0x100
   Flash:      origin = 0x10000,       len = 0x7f0000
   SDRAM:      origin = 0x940000,      len = 0x6c0000
   FLASHMIRROR: origin = 0x800000,     len = 0x4000
   MAILBOX:    origin = 0x100,         len = 0x400
   SDRAM_1:    origin = 0x804000,      len = 0x1c000
   SDRAM_2:    origin = 0x820000,      len = 0x20000
   SDRAM_3:    origin = 0x840000,      len = 0x20000
   SDRAM_4:    origin = 0x860000,      len = 0x20000
   SDRAM_5:    origin = 0x880000,      len = 0x20000
   SDRAM_6:    origin = 0x8a9000,      len = 0x17000
   SDRAM_7:    origin = 0x8c0000,      len = 0x20000
   SDRAM_8:    origin = 0x8e0000,      len = 0x20000
   SDRAM_9:    origin = 0x900000,      len = 0x20000
   SDRAM_10:   origin = 0x920000,      len = 0x20000
   DARAM_VOC:  origin = 0x5000,        len = 0xac00
   TREL_SECT:  origin = 0x00fc00,	   len = 0x000100	
   VOC_STORE:  origin = 0x8a0000,      len = 0x9000
}

/* MODULE CLK */
SECTIONS {
   .clk: block(0x20000){
        _CLK_start = _CLK_start5502;
        CLK_F_gethtime = CLK_F_getBIOStime;
        CLK_A_TABBEG = .;
        *(.clk)
        CLK_A_TABEND = .;
        CLK_A_TABLEN = (. - CLK_A_TABBEG) / 2;
   } > DARAM 
}
_CLK_PRD = CLK_PRD;
_CLK_PRDHIGH = CLK_PRDHIGH;
_CLK_COUNTSPMS = CLK_COUNTSPMS;
_CLK_REGS = CLK_REGS;
_CLK_USETIMER = CLK_USETIMER;
_CLK_TIMERNUM = CLK_TIMERNUM;
_CLK_TCR = CLK_TCR;
_CLK_TDDR = CLK_TDDR;
_CLK_TDDRHIGH = CLK_TDDRHIGH;

/* MODULE PRD */
SECTIONS {
   .prd: block(0x20000){
        PRD_A_TABBEG = .;
        /* no PRD objects */
        PRD_A_TABEND = .;
        PRD_A_TABLEN = (. - PRD_A_TABBEG) / 20;
   } > SDRAM
}

/* MODULE RTDX */
_RTDX_interrupt_mask = 0x0;

/* MODULE HWI */
HWI_TINT = HWI_INT4;
_HWI_TINT = HWI_TINT;
/* MODULE SWI */
SECTIONS {
   .swi: block(0x20000){
        SWI_A_TABBEG = .;
        *(.swi)
        SWI_A_TABEND = .;
        SWI_A_TABLEN = (. - SWI_A_TABBEG) / 22;
   } > DARAM
}

/* MODULE IDL */
SECTIONS {
   .idl: block(0x20000){
        IDL_A_TABBEG = .;
        *(.idl)
        IDL_A_TABEND = .;
        IDL_A_TABLEN = (. - IDL_A_TABBEG) / 4;
        IDL_A_CALBEG = .;
        *(.idlcal)
        IDL_A_CALEND = .;
        IDL_A_CALLEN = (. - IDL_A_CALBEG) / 4;
   } > DARAM
}



SECTIONS {
 /* RTA_toHost buffer */
.hst0: block(0x20000) align = 0x4 {} > DARAM
 
        .hst: {
             HST_A_TABBEG = .;
            _HST_A_TABBEG = .;
            *(.hst)
            HST_A_TABEND = .;
            _HST_A_TABEND = .;
             HST_A_TABLEN = (. - _HST_A_TABBEG) / 8;
            _HST_A_TABLEN = (. - _HST_A_TABBEG) / 8;
        } > DARAM
        
        /* trace buffer */
        .trace$buf: block(0x20000) align = 0x80 fill = 0xffff {} > DARAM
        
        .dsm: block(0x20000) {} > DARAM
        
        .stack: block(0x20000) fill=0xbeef {
            GBL_stackbeg = .;
            *(.stack)
            GBL_stackend = (GBL_stackbeg + 0x1400 - 1) ;
            _HWI_STKBOTTOM = (GBL_stackend+1);
            _HWI_STKTOP = (GBL_stackbeg);
        } > DARAM
        
        .log: {
             LOG_A_TABBEG = .;
            _LOG_A_TABBEG = .;
            *(.log)
            LOG_A_TABEND = .;
            _LOG_A_TABEND = .;
             LOG_A_TABLEN = (. - _LOG_A_TABBEG) / 20;
            _LOG_A_TABLEN = (. - _LOG_A_TABBEG) / 20;
        } > DARAM
        
        .pip: {
             PIP_A_TABBEG = .;
            _PIP_A_TABBEG = .;
            *(.pip)
            PIP_A_TABEND = .;
            _PIP_A_TABEND = .;
             PIP_A_TABLEN = (. - _PIP_A_TABBEG) / 100;
            _PIP_A_TABLEN = (. - _PIP_A_TABBEG) / 100;
        } > DARAM
        
        /* RxPipe buffer */
        .pip0: block(0x20000){} > DARAM
        
       /* RTA_fromHost buffer */
       .hst1: block(0x20000) align = 0x4 {} > DARAM
        
        .trace: block(0x20000) fill = 0x0 {
           _SYS_PUTCBEG = .;
           . += 0x200;
           _SYS_PUTCEND = . - 1;
        } > DARAM
        
        .rtdx_data: block(0x20000){}  > DARAM
        
        .sts: {
             STS_A_TABBEG = .;
            _STS_A_TABBEG = .;
            *(.sts)
            STS_A_TABEND = .;
            _STS_A_TABEND = .;
             STS_A_TABLEN = (. - _STS_A_TABBEG) / 16;
            _STS_A_TABLEN = (. - _STS_A_TABBEG) / 16;
        } > DARAM
        
        .printf (COPY): {} > DARAM
        
        /* LOG_system buffer */
        .LOG_system$buf: block(0x20000) align = 0x80 fill = 0xffff {} > DARAM
        
        .hwi_disp_sec:     {} > SDRAM
        
        .sysdata: block(0x20000) {} > SDRAM
        
        .hwi:  {}  > SDRAM
        
        .rtdx_text: {}  > SDRAM
        
        .bios:    {} > SDRAM
        
        .sysregs: {} > SDRAM
        
        .sysinit:    {} > SDRAM
        
        .mem: 	  {} > SDRAM
        
        .args: align = 0x4  fill=0 block(0x20000) {
            *(.args)
            . += 0x10;
        } > SDRAM
        
        .gblinit: block(0x20000)   {} > SDRAM
        
        .trcdata:    {} > SDRAM
        
        .csldata: block(0x20000) {
            *(.csldata)
        } > SDRAM
        
        .gio: block(0x20000)    {} > SDRAM
        
        .sys: block(0x20000)    {} > SDRAM
        
        .tsk: block(0x20000){
            *(.tsk)
        } > SDRAM_3
        
        .TSK_idle$stk: block(0x20000){
            *(.TSK_idle$stk)
        } > SDRAM_3
        
        .SDRAM_3$heap: {
            SDRAM_3$B = .;
            _SDRAM_3_base = .;
/*            SDRAM_3$L = 0x1e000;
            _SDRAM_3_length = 0x1e000;
            . += 0x1e000; */
            SDRAM_3$L = 0x1ef00;
            _SDRAM_3_length = 0x1ef00;
            . += 0x1ef00;
        } > SDRAM_3
        
        .hwi_vec:  align = 0x100{
            HWI_A_VECS = .;
           _HWI_A_VECS = . ; 
           *(.hwi_vec)
        } > VECT
        
}


