
/* ************************************************************************* */
/*
 *	idents.h
 *
 *	(C) 1994 - 2006 VOCAL Technologies, Ltd.
 *
 *	ALL RIGHTS RESERVED.  PROPRIETARY AND CONFIDENTIAL.
 *
 *	VOCAL Technologies, Ltd.
 *	90A John Muir Drive.
 *	Buffalo, NY  14228
 *
 *	Product:	MODEM 101
 *
 *	Module:		INCLUDE
 *
 *	This file contains the ident codes.
 *
 *	Revision Number:	$Revision$
 *	Revision Status:	$State$
 *	Last Modified:		$Date$
 *	Identification:		$Id$
 *
 *	Revision History:	$Log$
 *	Revision History:	Revision 1.1.6.2  2009/04/28 19:50:34  zhangn1
 *	Revision History:	SCR #173564. 2490H Vocal upgrade to Rev 4.56C
 *	Revision History:	
 *
 */
/* ************************************************************************* */

#ifndef _INCLUDE_IDENTS_H
#define _INCLUDE_IDENTS_H

/* ************************************************************************* */

#define THREAD__TX_DATA								0
#define THREAD__TX_BAUD								1
#define THREAD__TX_SAMPLE							2
#define THREAD__RX_SAMPLE							3
#define THREAD__RX_BAUD								4
#define THREAD__RX_DATA								5
#define THREAD__RX_UPDATE							6
#define THREAD__TX_B1								7
#define THREAD__RX_B1								8
#define THREAD__TX_B2								9
#define THREAD__RX_B2								10
#define THREAD__TX_D								11
#define THREAD__RX_D								12

#define THREAD__LAST								12

#define THREAD__MAX									15		/* Last possible thread ident */

#define IDENT(priority, thread, owner)	 (((unsigned) owner * 0x1000) + (priority * 0x0010) + thread)

/* ************************************************************************* */
/*
 *	Define transmit data thread element ordering
 *
 */
#define IDENT__TX_DATA__BAUD_DATA					IDENT (10, THREAD__TX_DATA, OWNER__FG_DATA)
#define IDENT__TX_DATA__BAUD_NRZI					IDENT (15, THREAD__TX_DATA, OWNER__FG_DATA)
#define IDENT__TX_DATA__V8_FRAME_DATA				IDENT (18, THREAD__TX_DATA, OWNER__FG_DATA)

#define IDENT__TX_DATA__LINE_INTERFACE				IDENT (20, THREAD__TX_DATA, OWNER__FG_DATA)
#define IDENT__TX_DATA__DTE_INTERFACE				IDENT (30, THREAD__TX_DATA, OWNER__FG_DATA)
#define IDENT__TX_DATA__SART_DATA					IDENT (30, THREAD__TX_DATA, OWNER__FG_DATA)
#define IDENT__TX_DATA__SPEECH_DIRECT				IDENT (30, THREAD__TX_DATA, OWNER__FG_SPEECH)

#define IDENT__TX_DATA__V13							IDENT (35, THREAD__TX_DATA, OWNER__FG_V13)
#define IDENT__TX_DATA__RDLB_GENERATOR				IDENT (40, THREAD__TX_DATA, OWNER__FG_RDLB)
#define IDENT__TX_DATA__TX_DATA_CLAMP				IDENT (50, THREAD__TX_DATA, OWNER__FG_MODULATION)
#define IDENT__TX_DATA__SCRAMBLER					IDENT (60, THREAD__TX_DATA, OWNER__FG_MODULATION)
#define IDENT__TX_DATA__BIT_8_INVERT				IDENT (70, THREAD__TX_DATA, OWNER__FG_MODULATION)
/*
 *	Define transmit baud thread element ordering
 *
 */

#define IDENT__TX_BAUD__B1_TRAIN_DATA				IDENT (9, THREAD__TX_BAUD, OWNER__FG_MODULATION)
#define IDENT__TX_BAUD__TX_CLOCK_PLL				IDENT (10, THREAD__TX_BAUD, OWNER__FG_MODULATION)
#define IDENT__TX_BAUD__TX_CLOCK_RESIDUE			IDENT (11, THREAD__TX_BAUD, OWNER__FG_MODULATION)
#define IDENT__TX_BAUD__TX_DATA_SOURCE				IDENT (20, THREAD__TX_BAUD, OWNER__FG_MODULATION)
#define IDENT__TX_BAUD__TX_DATA_CLAMP				IDENT (30, THREAD__TX_BAUD, OWNER__FG_MODULATION)
#define IDENT__TX_BAUD__SCRAMBLER					IDENT (40, THREAD__TX_BAUD, OWNER__FG_MODULATION)
#define IDENT__TX_BAUD__BIT_8_INVERT				IDENT (50, THREAD__TX_BAUD, OWNER__FG_MODULATION)
#define IDENT__TX_BAUD__COMFORT_NOISE				IDENT (55, THREAD__TX_BAUD, OWNER__FG_MODULATION)
#define IDENT__TX_BAUD__MASK						IDENT (60, THREAD__TX_BAUD, OWNER__FG_MODULATION)
#define IDENT__TX_BAUD__SPEECH_DECODER				IDENT (65, THREAD__TX_BAUD, OWNER__FG_MODULATION)
#define IDENT__TX_BAUD__DIFFERENTIAL_ENCODER		IDENT (70, THREAD__TX_BAUD, OWNER__FG_MODULATION)
#define IDENT__TX_BAUD__TRELLIS_ENCODER				IDENT (80, THREAD__TX_BAUD, OWNER__FG_MODULATION)
#define IDENT__TX_BAUD__EYE_MAP						IDENT (90, THREAD__TX_BAUD, OWNER__FG_MODULATION)

#define IDENT__TX_BAUD__PARSER						IDENT (100, THREAD__TX_BAUD, OWNER__FG_MODULATION)
#define IDENT__TX_BAUD__ENCODER1					IDENT (110, THREAD__TX_BAUD, OWNER__FG_MODULATION)
#define IDENT__TX_BAUD__ENCODER2					IDENT (120, THREAD__TX_BAUD, OWNER__FG_MODULATION)

#define IDENT__TX_BAUD__BULK_DELAY_INPUT			IDENT (130, THREAD__TX_BAUD, OWNER__FG_MODULATION)

#define IDENT__TX_BAUD__BONDING						IDENT (10, THREAD__TX_BAUD, OWNER__FG_BONDING)
/*
 *	Define transmit sample thread element ordering
 *
 */
#define IDENT__TX_SAMPLE__SCRAMBLER					IDENT (3, THREAD__TX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__TX_SAMPLE__PARSER					IDENT (5, THREAD__TX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__TX_SAMPLE__ENCODER					IDENT (7, THREAD__TX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__TX_SAMPLE__BULK_DELAY_OUTPUT			IDENT (10, THREAD__TX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__TX_SAMPLE__MODULATOR					IDENT (20, THREAD__TX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__TX_SAMPLE__TX_PASSBAND_FILTER		IDENT (30, THREAD__TX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__TX_SAMPLE__TONE_GENERATORS			IDENT (40, THREAD__TX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__TX_SAMPLE__OUTPUT_MODIFIER			IDENT (50, THREAD__TX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__TX_SAMPLE__RATE_CONVERSION			IDENT (60, THREAD__TX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__TX_SAMPLE__NOISE_GENERATOR			IDENT (70, THREAD__TX_SAMPLE, OWNER__FG_MODULATION)

#define IDENT__TX_SAMPLE__ISDN						IDENT (10, THREAD__TX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__TX_SAMPLE__BONDING1					IDENT (20, THREAD__TX_SAMPLE, OWNER__FG_BONDING)
#define IDENT__TX_SAMPLE__BONDING2					IDENT (30, THREAD__TX_SAMPLE, OWNER__FG_BONDING)

#define IDENT__TX_SAMPLE__SPEECH_DIRECT				IDENT (50, THREAD__TX_SAMPLE, OWNER__FG_SPEECH)
#define IDENT__TX_SAMPLE__LOOPBACK					IDENT (80, THREAD__TX_SAMPLE, OWNER__FG_MODULATION)

/*
 *	Define receive sample thread element ordering
 *
 */

#define IDENT__RX_SAMPLE__NOISE_GENERATOR			IDENT (5, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__RATE_CONVERSION			IDENT (10, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__ENERGY_MONITOR			IDENT (19, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__INPUT_FILTER				IDENT (20, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__SILENCE_DETECTOR			IDENT (30, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__ENERGY_DETECTOR			IDENT (40, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__ECHO_PREDICTION			IDENT (49, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__ECHO_REMOVAL				IDENT (50, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__PRE_EQUALIZER				IDENT (60, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__DEMODULATOR				IDENT (70, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__AGC_2_UPDATE				IDENT (71, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__RETRAIN_DETECTOR			IDENT (72, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__V17_SEQUENCE_DETECTOR		IDENT (73, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__V17_TIMING_DISPLAY		IDENT (74, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__S1_DETECTORS				IDENT (80, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__PHASE_ROLL_TRACKING		IDENT (90, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__AGC_PHASE_ROLL_MONITOR	IDENT (92, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)

#define IDENT__RX_SAMPLE__TONE_DETECTORS			IDENT (100, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__RECEIVE_INTERPOLATOR		IDENT (100, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)

#define IDENT__RX_SAMPLE__BAUD_TIMING_CONTROL		IDENT (101, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__AGC_BAUD_UPDATE			IDENT (102, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__CC_PROCESSING				IDENT (110, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__PCM0_INTERPOLATOR			IDENT (111, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__PCM1_INTERPOLATOR			IDENT (112, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__PCM_DECISION				IDENT (113, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__PCM_TRN2_MONITOR			IDENT (114, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__PCM_DECODER				IDENT (115, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__VDET_TRACKING				IDENT (120, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__LOOPBACK					IDENT (130, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)

#define IDENT__RX_SAMPLE__EC_COEF_UPDATE			IDENT (95, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)

#define IDENT__RX_SAMPLE__ISDN						IDENT (10, THREAD__RX_SAMPLE, OWNER__FG_MODULATION)
#define IDENT__RX_SAMPLE__BONDING1					IDENT (20, THREAD__RX_SAMPLE, OWNER__FG_BONDING)
#define IDENT__RX_SAMPLE__BONDING2					IDENT (30, THREAD__RX_SAMPLE, OWNER__FG_BONDING)
#define IDENT__RX_SAMPLE__BONDING3					IDENT (40, THREAD__RX_SAMPLE, OWNER__FG_BONDING)

#define IDENT__RX_SAMPLE__SPEECH_DIRECT				IDENT (50, THREAD__RX_SAMPLE, OWNER__FG_SPEECH)

/*
 *	Define receive baud thread element ordering
 *
 */
#define IDENT__RX_BAUD__PHASE_TRACKING				IDENT (10, THREAD__RX_BAUD, OWNER__FG_MODULATION)
#define IDENT__RX_BAUD__RECEIVE_INTERPOLATOR		IDENT (20, THREAD__RX_BAUD, OWNER__FG_MODULATION)
#define IDENT__RX_BAUD__EQUALIZER					IDENT (30, THREAD__RX_BAUD, OWNER__FG_MODULATION)
#define IDENT__RX_BAUD__DECISION					IDENT (40, THREAD__RX_BAUD, OWNER__FG_MODULATION)
#define IDENT__RX_BAUD__V34_TRN2_MONITOR			IDENT (45, THREAD__RX_BAUD, OWNER__FG_MODULATION)
#define IDENT__RX_BAUD__DIFFERENTIAL_DECODER		IDENT (50, THREAD__RX_BAUD, OWNER__FG_MODULATION)
#define IDENT__RX_BAUD__SPEECH_ENCODER				IDENT (55, THREAD__RX_BAUD, OWNER__FG_MODULATION)
#define IDENT__RX_BAUD__BIT_8_INVERT				IDENT (60, THREAD__RX_BAUD, OWNER__FG_MODULATION)
#define IDENT__RX_BAUD__SPEECH_DETECTOR				IDENT (65, THREAD__RX_BAUD, OWNER__FG_MODULATION)
#define IDENT__RX_BAUD__DESCRAMBLER					IDENT (70, THREAD__RX_BAUD, OWNER__FG_MODULATION)
#define IDENT__RX_BAUD__RATE_SEQUENCE_DETECTOR		IDENT (80, THREAD__RX_BAUD, OWNER__FG_MODULATION)
#define IDENT__RX_BAUD__RX_DATA_CLAMP				IDENT (90, THREAD__RX_BAUD, OWNER__FG_MODULATION)
#define IDENT__RX_BAUD__RX_DATA_DUMP				IDENT (100, THREAD__RX_BAUD, OWNER__FG_MODULATION)

#define IDENT__RX_BAUD__PRE_DECODER1				IDENT (115, THREAD__RX_BAUD, OWNER__FG_MODULATION)
#define IDENT__RX_BAUD__DECODER1					IDENT (120, THREAD__RX_BAUD, OWNER__FG_MODULATION)
#define IDENT__RX_BAUD__POST_DECODER1				IDENT (125, THREAD__RX_BAUD, OWNER__FG_MODULATION)
#define IDENT__RX_BAUD__DECODER2					IDENT (130, THREAD__RX_BAUD, OWNER__FG_MODULATION)
#define IDENT__RX_BAUD__SHAPER						IDENT (140, THREAD__RX_BAUD, OWNER__FG_MODULATION)

#define IDENT__RX_BAUD__BAUD_TIMING_CONTROL			IDENT (150, THREAD__RX_BAUD, OWNER__FG_MODULATION)

#define IDENT__RX_BAUD__RETRAIN_DETECTOR			IDENT (160, THREAD__RX_BAUD, OWNER__FG_MODULATION)
#define IDENT__RX_BAUD__POLYNOMIAL_DETECTOR			IDENT (170, THREAD__RX_BAUD, OWNER__FG_MODULATION)

#define IDENT__RX_BAUD__BONDING						IDENT (10, THREAD__RX_BAUD, OWNER__FG_BONDING)

#define IDENT__RX_BAUD__VDET_TRACKING				IDENT (180, THREAD__RX_BAUD, OWNER__FG_MODULATION)

#define IDENT__FAX_SYMBOL_TRACKING					IDENT__RX_BAUD__BAUD_TIMING_CONTROL + 0x0010
#define IDENT__FAX_SAMPLE_TRACKING					IDENT__RX_SAMPLE__DEMODULATOR + 0x0010

/*
 *	Define receive data thread element ordering
 *
 */
#define IDENT__RX_DATA__BIT_8_INVERT				IDENT (10, THREAD__RX_DATA, OWNER__FG_MODULATION)
#define IDENT__RX_DATA__DESCRAMBLER					IDENT (20, THREAD__RX_DATA, OWNER__FG_MODULATION)
#define IDENT__RX_DATA__RX_DATA_CLAMP				IDENT (30, THREAD__RX_DATA, OWNER__FG_MODULATION)
#define IDENT__RX_DATA__RDLB_DETECTOR				IDENT (40, THREAD__RX_DATA, OWNER__FG_RDLB)
#define IDENT__RX_DATA__V13							IDENT (45, THREAD__RX_DATA, OWNER__FG_V13)
#define IDENT__RX_DATA__BAUD_NRZI					IDENT (47, THREAD__RX_DATA, OWNER__FG_DATA)
#define IDENT__RX_DATA__BAUD_DATA					IDENT (50, THREAD__RX_DATA, OWNER__FG_DATA)
#define IDENT__RX_DATA__LINE_INTERFACE				IDENT (60, THREAD__RX_DATA, OWNER__FG_DATA)
#define IDENT__RX_DATA__DTE_INTERFACE				IDENT (70, THREAD__RX_DATA, OWNER__FG_DATA)
#define IDENT__RX_DATA__V8_FRAME_DATA				IDENT (55, THREAD__RX_DATA, OWNER__FG_DATA)
#define IDENT__RX_DATA__SART_DATA					IDENT (80, THREAD__RX_DATA, OWNER__FG_DATA)
#define IDENT__RX_DATA__SPEECH_DIRECT				IDENT (80, THREAD__RX_DATA, OWNER__FG_SPEECH)

/*
 *	Define receive update thread element ordering
 *
 */
#define IDENT__UPDATE__TRAIN_ON_DATA				IDENT (10, THREAD__RX_UPDATE, OWNER__FG_MODULATION)
#define IDENT__UPDATE__EQUALIZER_UPDATE				IDENT (20, THREAD__RX_UPDATE, OWNER__FG_MODULATION)
#define IDENT__UPDATE__EC_COEF_UPDATE				IDENT (30, THREAD__RX_UPDATE, OWNER__FG_MODULATION)
#define IDENT__UPDATE__AGC_PHASE_ROLL_UPDATE		IDENT (40, THREAD__RX_UPDATE, OWNER__FG_MODULATION)
#define IDENT__UPDATE__AGC_PHASE_ROLL_MONITOR		IDENT (42, THREAD__RX_UPDATE, OWNER__FG_MODULATION)
#define IDENT__UPDATE__AGC_1_UPDATE					IDENT (50, THREAD__RX_UPDATE, OWNER__FG_MODULATION)
#define IDENT__UPDATE__AGC_2_UPDATE					IDENT (60, THREAD__RX_UPDATE, OWNER__FG_MODULATION)
#define IDENT__UPDATE__AGC_BAUD_UPDATE				IDENT (70, THREAD__RX_UPDATE, OWNER__FG_MODULATION)
#define IDENT__UPDATE__STATISTICS					IDENT (80, THREAD__RX_UPDATE, OWNER__FG_MODULATION)
#define IDENT__UPDATE__DCD_CONTROL					IDENT (90, THREAD__RX_UPDATE, OWNER__FG_MODULATION)
#define IDENT__UPDATE__ANTI_LOCK					IDENT (100, THREAD__RX_UPDATE, OWNER__FG_MODULATION)

/* ************************************************************************* */
/*
 *	Define transmit line thread element ordering
 *
 */
#define IDENT__TX_B1__RATE_CONVERSION				IDENT (10, THREAD__TX_B1, OWNER__FG_ISDN)
#define IDENT__TX_B1__SAMPLE_COUNTER				IDENT (20, THREAD__TX_B1, OWNER__FG_ISDN)
#define IDENT__TX_B1__DTMF_GENERATOR				IDENT (30, THREAD__TX_B1, OWNER__FG_TEL)
#define IDENT__TX_B1__PRIORITY_GENERATOR			IDENT (40, THREAD__TX_B1, OWNER__FG_TEL)
#define IDENT__TX_B1__LINE_GAIN						IDENT (45, THREAD__TX_B1, OWNER__FG_TEL)
#define IDENT__TX_B1__ECHO_CANCELLER				IDENT (50, THREAD__TX_B1, OWNER__FG_TEL)
#define IDENT__TX_B1__IMPEDANCE_MONITOR				IDENT (55, THREAD__TX_B1, OWNER__FG_TEL)
#define IDENT__TX_B1__POWER_MEASURMENT				IDENT (60, THREAD__TX_B1, OWNER__FG_ISDN)
#define IDENT__TX_B1__PLC_PRECALC					IDENT (65, THREAD__TX_B1, OWNER__FG_SPEECH)
#define IDENT__TX_B1__RECORD_SAMPLE					IDENT (70, THREAD__TX_B1, OWNER__FG_ISDN)
#define IDENT__TX_B1__SAMPLE_HOOK					IDENT (75, THREAD__TX_B1, OWNER__FG_ISDN)
#define IDENT__TX_B1__PCM_ENCODE					IDENT (80, THREAD__TX_B1, OWNER__FG_ISDN)
#define IDENT__TX_B1__ROBBED_BIT					IDENT (90, THREAD__TX_B1, OWNER__FG_ISDN)
#define IDENT__TX_B1__BIT_REVERSE					IDENT (100, THREAD__TX_B1, OWNER__FG_ISDN)
#define IDENT__TX_B1__LINE_FORMAT					IDENT (110, THREAD__TX_B1, OWNER__FG_ISDN)
/*
 *	Define receive line thread element ordering
 *
 */
#define IDENT__RX_B1__LINE_FORMAT					IDENT (10, THREAD__RX_B1, OWNER__FG_ISDN)
#define IDENT__RX_B1__BIT_REVERSE					IDENT (20, THREAD__RX_B1, OWNER__FG_ISDN)
#define IDENT__RX_B1__ROBBED_BIT					IDENT (30, THREAD__RX_B1, OWNER__FG_ISDN)
#define IDENT__RX_B1__PCM_DECODE					IDENT (40, THREAD__RX_B1, OWNER__FG_ISDN)
#define IDENT__RX_B1__SAMPLE_HOOK					IDENT (45, THREAD__RX_B1, OWNER__FG_ISDN)
#define IDENT__RX_B1__RECORD_SAMPLE					IDENT (50, THREAD__RX_B1, OWNER__FG_ISDN)
#define IDENT__RX_B1__SPEECH_PLC					IDENT (55, THREAD__RX_B1, OWNER__FG_ISDN)
#define IDENT__RX_B1__POWER_MEASURMENT				IDENT (60, THREAD__RX_B1, OWNER__FG_ISDN)
#define IDENT__RX_B1__IMPEDANCE_MONITOR				IDENT (65, THREAD__RX_B1, OWNER__FG_TEL)
#define IDENT__RX_B1__ECHO_CANCELLER				IDENT (70, THREAD__RX_B1, OWNER__FG_TEL)
#define IDENT__RX_B1__CMR_NOTCH						IDENT (75, THREAD__RX_B1, OWNER__FG_TEL)
#define IDENT__RX_B1__DTMF_DETECTOR					IDENT (80, THREAD__RX_B1, OWNER__FG_TEL)
#define IDENT__RX_B1__FAXDET_DETECTOR				IDENT (85, THREAD__RX_B1, OWNER__FG_AUTOMODE)
#define IDENT__RX_B1__CP_DETECTOR					IDENT (87, THREAD__RX_B1, OWNER__FG_MODULATION)
#define IDENT__RX_B1__LINE_GAIN						IDENT (90, THREAD__RX_B1, OWNER__FG_TEL)
#define IDENT__RX_B1__AUDIO_AGC						IDENT (95, THREAD__RX_B1, OWNER__FG_SPEECH)
#define IDENT__RX_B1__RATE_CONVERSION				IDENT (100, THREAD__RX_B1, OWNER__FG_ISDN)

/* ************************************************************************* */
/*
 *	Define transmit B2 thread element ordering
 *
 */
#define IDENT__TX_B2__BAUD							IDENT (10, THREAD__TX_B2, OWNER__FG_ISDN)
#define IDENT__TX_B2__V110							IDENT (20, THREAD__TX_B2, OWNER__FG_ISDN)
#define IDENT__TX_B2__BONDING						IDENT (30, THREAD__TX_B2, OWNER__FG_ISDN)
#define IDENT__TX_B2__ISDN							IDENT (40, THREAD__TX_B2, OWNER__FG_ISDN)
#define IDENT__TX_B2__SART							IDENT (50, THREAD__TX_B2, OWNER__FG_ISDN)
#define IDENT__TX_B2__SPEAKERPHONE_SOURCE			IDENT (60, THREAD__TX_B2, OWNER__FG_TEL)
#define IDENT__TX_B2__ECHO_CANCELLER				IDENT (70, THREAD__TX_B2, OWNER__FG_TEL)
#define IDENT__TX_B2__DTMF_GENERATOR				IDENT (75, THREAD__TX_B2, OWNER__FG_TEL)
#define IDENT__TX_B2__SPEAKER_GAIN					IDENT (80, THREAD__TX_B2, OWNER__FG_TEL)
/*
 *	Define receive B2 thread element ordering
 *
 */
#define IDENT__RX_B2__ISDN							IDENT (10, THREAD__RX_B2, OWNER__FG_ISDN)
#define IDENT__RX_B2__BONDING						IDENT (20, THREAD__RX_B2, OWNER__FG_ISDN)
#define IDENT__RX_B2__V110							IDENT (30, THREAD__RX_B2, OWNER__FG_ISDN)
#define IDENT__RX_B2__BAUD							IDENT (40, THREAD__RX_B2, OWNER__FG_ISDN)
#define IDENT__RX_B2__SART							IDENT (50, THREAD__RX_B2, OWNER__FG_ISDN)
#define IDENT__RX_B2__MICROPHONE_GAIN				IDENT (60, THREAD__RX_B2, OWNER__FG_TEL)
#define IDENT__RX_B2__DTMF_DETECTOR					IDENT (65, THREAD__RX_B2, OWNER__FG_TEL)
#define IDENT__RX_B2__ECHO_CANCELLER				IDENT (70, THREAD__RX_B2, OWNER__FG_TEL)
#define IDENT__RX_B2__SPEAKERPHONE_SOURCE			IDENT (80, THREAD__RX_B2, OWNER__FG_TEL)

/* ************************************************************************* */
/*
 *	Define transmit D thread element ordering
 *
 */
#define IDENT__TX_D__ISDN							IDENT (10, THREAD__TX_D, OWNER__FG_ISDN)
#define IDENT__TX_D__XX2							IDENT (20, THREAD__TX_D, OWNER__FG_ISDN)
#define IDENT__TX_D__XX3							IDENT (30, THREAD__TX_D, OWNER__FG_ISDN)
#define IDENT__TX_D__XX4							IDENT (40, THREAD__TX_D, OWNER__FG_ISDN)
#define IDENT__TX_D__XX5							IDENT (50, THREAD__TX_D, OWNER__FG_ISDN)
/*
 *	Define receive D thread element ordering
 *
 */
#define IDENT__RX_D__ISDN							IDENT (10, THREAD__RX_D, OWNER__FG_ISDN)
#define IDENT__RX_D__XX2							IDENT (20, THREAD__RX_D, OWNER__FG_ISDN)
#define IDENT__RX_D__XX3							IDENT (30, THREAD__RX_D, OWNER__FG_ISDN)
#define IDENT__RX_D__XX4							IDENT (40, THREAD__RX_D, OWNER__FG_ISDN)
#define IDENT__RX_D__XX5							IDENT (50, THREAD__RX_D, OWNER__FG_ISDN)

/* ************************************************************************* */

#endif /* _INCLUDE_IDENTS_H */
