/* Copyright (c) 2001 by Medtronic Inc.  All Rights Reserved */
/********************************************************************
DOCUMENT

$Revision$
$Date$
$RCSfile$

GENERATED FROM FILE:    tbm_autoid.fsm
GENERATED BY:           State Map Compiler (SMC)
                        (version: 3.0)
GENERATED USING SCRIPT: c.sms,v
                        (version: 1.5)
GENERATED ON:           2001-05-24   AT: 13:20:04

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                 !!
!!                          W A R N I N G                          !!
!!                                                                 !!
!!   This file must NOT be changed  manually.  If changes to its   !!
!!   contents are  needed,  the  changes  should  be made to the   !!
!!   corresponding  .fsm file  (identified above) and  the  .h/c   !!
!!   should be regenerated using the SMC tool.                     !!
!!                                                                 !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

ENDDOCUMENT
********************************************************************/

#ifndef tbm_autoid_h
#define tbm_autoid_h

/********************************************************************
DOCUMENT

FINITE STATE MACHINE: tbm_AutoID

  This file contains the generated C declarations for
  Finite State Machine (FSM) tbm_AutoID.

ENDDOCUMENT
********************************************************************/

struct tbm_AutoID_StateObject;  /* forward declaration of internal-to-implementation type */

typedef struct tbm_AutoID
{

    const struct tbm_AutoID_StateObject *p_currentState;

}
tbm_AutoID;

void tbm_AutoID_initialize(struct tbm_AutoID *p_fsm);
const char *tbm_AutoID_stateName(struct tbm_AutoID *p_fsm);

void tbm_AutoID_RespTimeout(struct tbm_AutoID *p_fsm);
void tbm_AutoID_UniqueRespRx(struct tbm_AutoID *p_fsm);

void tbm_concludeAutoID(struct tbm_AutoID *p_fsm);
void tbm_continueAutoID(struct tbm_AutoID *p_fsm);

#endif /* tbm_autoid_h */
