/* Copyright (c) 2002 by Medtronic Inc.  All Rights Reserved */
/********************************************************************
DOCUMENT

$Revision$
$Date$
$RCSfile$

GENERATED FROM FILE:    tbm_fsm.fsm
GENERATED BY:           State Map Compiler (SMC)
                        (version: 3.0)
GENERATED USING SCRIPT: c.sms,v
                        (version: 1.5)
GENERATED ON:           2002-01-15   AT: 10:07:22

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                 !!
!!                          W A R N I N G                          !!
!!                                                                 !!
!!   This file must NOT be changed  manually.  If changes to its   !!
!!   contents are  needed,  the  changes  should  be made to the   !!
!!   corresponding  .fsm file  (identified above) and  the  .h/c   !!
!!   should be regenerated using the SMC tool.                     !!
!!                                                                 !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

ENDDOCUMENT
********************************************************************/


#include "tbm_fsm.h"




/********************************************************************
DOCUMENT

FINITE STATE MACHINE: tbm_Chan

  This file contains the generated C implementation for
  Finite State Machine (FSM) tbm_Chan.

ENDDOCUMENT
********************************************************************/



/**************************************************************
  State object type declaration.
**************************************************************/



/**************************************************************
  Declarations for FSM transition functions.
**************************************************************/

static void  ActivateTelemB_Common            (struct tbm_Chan* p_fsm);
static void  ActivateTelemB_Idle              (struct tbm_Chan* p_fsm);
static void  AppDataFFTxDone_Common           (struct tbm_Chan* p_fsm);
static void  AppDataRequest_Common            (struct tbm_Chan* p_fsm);
static void  AppDataRequest_Mode1Hold         (struct tbm_Chan* p_fsm);
static void  AppDataRequest_Mode2             (struct tbm_Chan* p_fsm);
static void  AppDataTxFail_Common             (struct tbm_Chan* p_fsm);
static void  AutoIDDone_AwaitDeviceIDResp     (struct tbm_Chan* p_fsm);
static void  AutoIDDone_Common                (struct tbm_Chan* p_fsm);
static void  AutoIDRequest_Common             (struct tbm_Chan* p_fsm);
static void  AutoIDRequest_Mode1Hold          (struct tbm_Chan* p_fsm);
static void  AutoIDRequest_Mode2              (struct tbm_Chan* p_fsm);
static void  CaptureDataDone_Common           (struct tbm_Chan* p_fsm);
static void  CaptureDataDone_Mode1            (struct tbm_Chan* p_fsm);
static void  CaptureDataFail_Common           (struct tbm_Chan* p_fsm);
static void  CaptureDataFail_Mode1            (struct tbm_Chan* p_fsm);
static void  CloseRequest_Common              (struct tbm_Chan* p_fsm);
static void  CloseRequest_Mode1Hold           (struct tbm_Chan* p_fsm);
static void  CloseRequest_Mode2               (struct tbm_Chan* p_fsm);
static void  CloseTxDone_Closing              (struct tbm_Chan* p_fsm);
static void  CloseTxDone_Common               (struct tbm_Chan* p_fsm);
static void  DataFrameUL_Common               (struct tbm_Chan* p_fsm);
static void  DataFrameUL_Mode1                (struct tbm_Chan* p_fsm);
static void  DeviceIDTxDone_Common            (struct tbm_Chan* p_fsm);
static void  DeviceIDTxDone_Mode2             (struct tbm_Chan* p_fsm);
static void  DeviceIDTx_AwaitDeviceIDResp     (struct tbm_Chan* p_fsm);
static void  DeviceIDTx_Common                (struct tbm_Chan* p_fsm);
static void  EndSession_Common                (struct tbm_Chan* p_fsm);
static void  FFTxDone_Common                  (struct tbm_Chan* p_fsm);
static void  FFTxDone_Mode1                   (struct tbm_Chan* p_fsm);
static void  MissedWF_Common                  (struct tbm_Chan* p_fsm);
static void  MissedWF_Mode1                   (struct tbm_Chan* p_fsm);
static void  OpenDone_AwaitOpenResp           (struct tbm_Chan* p_fsm);
static void  OpenDone_Common                  (struct tbm_Chan* p_fsm);
static void  OpenFail_AwaitOpenResp           (struct tbm_Chan* p_fsm);
static void  OpenFail_Common                  (struct tbm_Chan* p_fsm);
static void  OpenTxDone_Common                (struct tbm_Chan* p_fsm);
static void  OpenTxDone_Mode2                 (struct tbm_Chan* p_fsm);
static void  RespTimeout_AwaitDeviceIDResp    (struct tbm_Chan* p_fsm);
static void  RespTimeout_AwaitOpenResp        (struct tbm_Chan* p_fsm);
static void  RespTimeout_Common               (struct tbm_Chan* p_fsm);
static void  RespTimeout_Mode1                (struct tbm_Chan* p_fsm);
static void  ShortTimeOut_AwaitOpenResp       (struct tbm_Chan* p_fsm);
static void  ShortTimeOut_Common              (struct tbm_Chan* p_fsm);
static void  ShortTimeOut_Mode1               (struct tbm_Chan* p_fsm);
static void  ShortTimeOut_Mode1Hold           (struct tbm_Chan* p_fsm);
static void  TxTimeout_Closing                (struct tbm_Chan* p_fsm);
static void  TxTimeout_Common                 (struct tbm_Chan* p_fsm);
static void  TxTimeout_Mode1                  (struct tbm_Chan* p_fsm);
static void  TxTimeout_Mode2                  (struct tbm_Chan* p_fsm);
static void  UnNumFrameUL_AwaitDeviceIDResp   (struct tbm_Chan* p_fsm);
static void  UnNumFrameUL_AwaitOpenResp       (struct tbm_Chan* p_fsm);
static void  UnNumFrameUL_Common              (struct tbm_Chan* p_fsm);
static void  UnNumFrameUL_Mode1               (struct tbm_Chan* p_fsm);
static void  UplinksRequest_AwaitDeviceIDResp (struct tbm_Chan* p_fsm);
static void  UplinksRequest_Common            (struct tbm_Chan* p_fsm);
static void  UplinksRequest_Mode1Hold         (struct tbm_Chan* p_fsm);
static void  UplinksRequest_Mode2             (struct tbm_Chan* p_fsm);
static void  WaveformUL_AwaitOpenResp         (struct tbm_Chan* p_fsm);
static void  WaveformUL_Common                (struct tbm_Chan* p_fsm);
static void  WaveformUL_Mode1                 (struct tbm_Chan* p_fsm);




/**************************************************************
  Transition Indices
**************************************************************/

#define  c_index_ActivateTelemB  0
#define  c_index_AppDataFFTxDone 1
#define  c_index_AppDataRequest  2
#define  c_index_AppDataTxFail   3
#define  c_index_AutoIDDone      4
#define  c_index_AutoIDRequest   5
#define  c_index_CaptureDataDone 6
#define  c_index_CaptureDataFail 7
#define  c_index_CloseRequest    8
#define  c_index_CloseTxDone     9
#define  c_index_DataFrameUL     10
#define  c_index_DeviceIDTx      11
#define  c_index_DeviceIDTxDone  12
#define  c_index_EndSession      13
#define  c_index_FFTxDone        14
#define  c_index_MissedWF        15
#define  c_index_OpenDone        16
#define  c_index_OpenFail        17
#define  c_index_OpenTxDone      18
#define  c_index_RespTimeout     19
#define  c_index_ShortTimeOut    20
#define  c_index_TxTimeout       21
#define  c_index_UnNumFrameUL    22
#define  c_index_UplinksRequest  23
#define  c_index_WaveformUL      24




/**************************************************************
  State object definitions.
**************************************************************/


static const struct tbm_Chan_StateObject v_stateAwaitDeviceIDResp = {
    "AwaitDeviceIDResp",
    { /* ActivateTelemB  */ &ActivateTelemB_Common,
                            /* AppDataFFTxDone */ &AppDataFFTxDone_Common,
                            /* AppDataRequest  */ &AppDataRequest_Common,
                            /* AppDataTxFail   */ &AppDataTxFail_Common,
                            /* AutoIDDone      */ &AutoIDDone_AwaitDeviceIDResp,
                            /* AutoIDRequest   */ &AutoIDRequest_Common,
                            /* CaptureDataDone */ &CaptureDataDone_Common,
                            /* CaptureDataFail */ &CaptureDataFail_Common,
                            /* CloseRequest    */ &CloseRequest_Common,
                            /* CloseTxDone     */ &CloseTxDone_Common,
                            /* DataFrameUL     */ &DataFrameUL_Common,
                            /* DeviceIDTx      */ &DeviceIDTx_AwaitDeviceIDResp,
                            /* DeviceIDTxDone  */ &DeviceIDTxDone_Common,
                            /* EndSession      */ &EndSession_Common,
                            /* FFTxDone        */ &FFTxDone_Common,
                            /* MissedWF        */ &MissedWF_Common,
                            /* OpenDone        */ &OpenDone_Common,
                            /* OpenFail        */ &OpenFail_Common,
                            /* OpenTxDone      */ &OpenTxDone_Common,
                            /* RespTimeout     */ &RespTimeout_AwaitDeviceIDResp,
                            /* ShortTimeOut    */ &ShortTimeOut_Common,
                            /* TxTimeout       */ &TxTimeout_Common,
                            /* UnNumFrameUL    */ &UnNumFrameUL_AwaitDeviceIDResp,
                            /* UplinksRequest  */ &UplinksRequest_AwaitDeviceIDResp,
                            /* WaveformUL      */ &WaveformUL_Common }
};

static const struct tbm_Chan_StateObject v_stateAwaitOpenResp = {
    "AwaitOpenResp",
    { /* ActivateTelemB  */ &ActivateTelemB_Common,
                            /* AppDataFFTxDone */ &AppDataFFTxDone_Common,
                            /* AppDataRequest  */ &AppDataRequest_Common,
                            /* AppDataTxFail   */ &AppDataTxFail_Common,
                            /* AutoIDDone      */ &AutoIDDone_Common,
                            /* AutoIDRequest   */ &AutoIDRequest_Common,
                            /* CaptureDataDone */ &CaptureDataDone_Common,
                            /* CaptureDataFail */ &CaptureDataFail_Common,
                            /* CloseRequest    */ &CloseRequest_Common,
                            /* CloseTxDone     */ &CloseTxDone_Common,
                            /* DataFrameUL     */ &DataFrameUL_Common,
                            /* DeviceIDTx      */ &DeviceIDTx_Common,
                            /* DeviceIDTxDone  */ &DeviceIDTxDone_Common,
                            /* EndSession      */ &EndSession_Common,
                            /* FFTxDone        */ &FFTxDone_Common,
                            /* MissedWF        */ &MissedWF_Common,
                            /* OpenDone        */ &OpenDone_AwaitOpenResp,
                            /* OpenFail        */ &OpenFail_AwaitOpenResp,
                            /* OpenTxDone      */ &OpenTxDone_Common,
                            /* RespTimeout     */ &RespTimeout_AwaitOpenResp,
                            /* ShortTimeOut    */ &ShortTimeOut_AwaitOpenResp,
                            /* TxTimeout       */ &TxTimeout_Common,
                            /* UnNumFrameUL    */ &UnNumFrameUL_AwaitOpenResp,
                            /* UplinksRequest  */ &UplinksRequest_Common,
                            /* WaveformUL      */ &WaveformUL_AwaitOpenResp }
};

static const struct tbm_Chan_StateObject v_stateClosing = {
    "Closing",
    { /* ActivateTelemB  */ &ActivateTelemB_Common,
                            /* AppDataFFTxDone */ &AppDataFFTxDone_Common,
                            /* AppDataRequest  */ &AppDataRequest_Common,
                            /* AppDataTxFail   */ &AppDataTxFail_Common,
                            /* AutoIDDone      */ &AutoIDDone_Common,
                            /* AutoIDRequest   */ &AutoIDRequest_Common,
                            /* CaptureDataDone */ &CaptureDataDone_Common,
                            /* CaptureDataFail */ &CaptureDataFail_Common,
                            /* CloseRequest    */ &CloseRequest_Common,
                            /* CloseTxDone     */ &CloseTxDone_Closing,
                            /* DataFrameUL     */ &DataFrameUL_Common,
                            /* DeviceIDTx      */ &DeviceIDTx_Common,
                            /* DeviceIDTxDone  */ &DeviceIDTxDone_Common,
                            /* EndSession      */ &EndSession_Common,
                            /* FFTxDone        */ &FFTxDone_Common,
                            /* MissedWF        */ &MissedWF_Common,
                            /* OpenDone        */ &OpenDone_Common,
                            /* OpenFail        */ &OpenFail_Common,
                            /* OpenTxDone      */ &OpenTxDone_Common,
                            /* RespTimeout     */ &RespTimeout_Common,
                            /* ShortTimeOut    */ &ShortTimeOut_Common,
                            /* TxTimeout       */ &TxTimeout_Closing,
                            /* UnNumFrameUL    */ &UnNumFrameUL_Common,
                            /* UplinksRequest  */ &UplinksRequest_Common,
                            /* WaveformUL      */ &WaveformUL_Common }
};

static const struct tbm_Chan_StateObject v_stateIdle = {
    "Idle",
    { /* ActivateTelemB  */ &ActivateTelemB_Idle,
                            /* AppDataFFTxDone */ &AppDataFFTxDone_Common,
                            /* AppDataRequest  */ &AppDataRequest_Common,
                            /* AppDataTxFail   */ &AppDataTxFail_Common,
                            /* AutoIDDone      */ &AutoIDDone_Common,
                            /* AutoIDRequest   */ &AutoIDRequest_Common,
                            /* CaptureDataDone */ &CaptureDataDone_Common,
                            /* CaptureDataFail */ &CaptureDataFail_Common,
                            /* CloseRequest    */ &CloseRequest_Common,
                            /* CloseTxDone     */ &CloseTxDone_Common,
                            /* DataFrameUL     */ &DataFrameUL_Common,
                            /* DeviceIDTx      */ &DeviceIDTx_Common,
                            /* DeviceIDTxDone  */ &DeviceIDTxDone_Common,
                            /* EndSession      */ &EndSession_Common,
                            /* FFTxDone        */ &FFTxDone_Common,
                            /* MissedWF        */ &MissedWF_Common,
                            /* OpenDone        */ &OpenDone_Common,
                            /* OpenFail        */ &OpenFail_Common,
                            /* OpenTxDone      */ &OpenTxDone_Common,
                            /* RespTimeout     */ &RespTimeout_Common,
                            /* ShortTimeOut    */ &ShortTimeOut_Common,
                            /* TxTimeout       */ &TxTimeout_Common,
                            /* UnNumFrameUL    */ &UnNumFrameUL_Common,
                            /* UplinksRequest  */ &UplinksRequest_Common,
                            /* WaveformUL      */ &WaveformUL_Common }
};

static const struct tbm_Chan_StateObject v_stateMode1 = {
    "Mode1",
    { /* ActivateTelemB  */ &ActivateTelemB_Common,
                            /* AppDataFFTxDone */ &AppDataFFTxDone_Common,
                            /* AppDataRequest  */ &AppDataRequest_Common,
                            /* AppDataTxFail   */ &AppDataTxFail_Common,
                            /* AutoIDDone      */ &AutoIDDone_Common,
                            /* AutoIDRequest   */ &AutoIDRequest_Common,
                            /* CaptureDataDone */ &CaptureDataDone_Mode1,
                            /* CaptureDataFail */ &CaptureDataFail_Mode1,
                            /* CloseRequest    */ &CloseRequest_Common,
                            /* CloseTxDone     */ &CloseTxDone_Common,
                            /* DataFrameUL     */ &DataFrameUL_Mode1,
                            /* DeviceIDTx      */ &DeviceIDTx_Common,
                            /* DeviceIDTxDone  */ &DeviceIDTxDone_Common,
                            /* EndSession      */ &EndSession_Common,
                            /* FFTxDone        */ &FFTxDone_Mode1,
                            /* MissedWF        */ &MissedWF_Mode1,
                            /* OpenDone        */ &OpenDone_Common,
                            /* OpenFail        */ &OpenFail_Common,
                            /* OpenTxDone      */ &OpenTxDone_Common,
                            /* RespTimeout     */ &RespTimeout_Mode1,
                            /* ShortTimeOut    */ &ShortTimeOut_Mode1,
                            /* TxTimeout       */ &TxTimeout_Mode1,
                            /* UnNumFrameUL    */ &UnNumFrameUL_Mode1,
                            /* UplinksRequest  */ &UplinksRequest_Common,
                            /* WaveformUL      */ &WaveformUL_Mode1 }
};

static const struct tbm_Chan_StateObject v_stateMode1Hold = {
    "Mode1Hold",
    { /* ActivateTelemB  */ &ActivateTelemB_Common,
                            /* AppDataFFTxDone */ &AppDataFFTxDone_Common,
                            /* AppDataRequest  */ &AppDataRequest_Mode1Hold,
                            /* AppDataTxFail   */ &AppDataTxFail_Common,
                            /* AutoIDDone      */ &AutoIDDone_Common,
                            /* AutoIDRequest   */ &AutoIDRequest_Mode1Hold,
                            /* CaptureDataDone */ &CaptureDataDone_Common,
                            /* CaptureDataFail */ &CaptureDataFail_Common,
                            /* CloseRequest    */ &CloseRequest_Mode1Hold,
                            /* CloseTxDone     */ &CloseTxDone_Common,
                            /* DataFrameUL     */ &DataFrameUL_Common,
                            /* DeviceIDTx      */ &DeviceIDTx_Common,
                            /* DeviceIDTxDone  */ &DeviceIDTxDone_Common,
                            /* EndSession      */ &EndSession_Common,
                            /* FFTxDone        */ &FFTxDone_Common,
                            /* MissedWF        */ &MissedWF_Common,
                            /* OpenDone        */ &OpenDone_Common,
                            /* OpenFail        */ &OpenFail_Common,
                            /* OpenTxDone      */ &OpenTxDone_Common,
                            /* RespTimeout     */ &RespTimeout_Common,
                            /* ShortTimeOut    */ &ShortTimeOut_Mode1Hold,
                            /* TxTimeout       */ &TxTimeout_Common,
                            /* UnNumFrameUL    */ &UnNumFrameUL_Common,
                            /* UplinksRequest  */ &UplinksRequest_Mode1Hold,
                            /* WaveformUL      */ &WaveformUL_Common }
};

static const struct tbm_Chan_StateObject v_stateMode2 = {
    "Mode2",
    { /* ActivateTelemB  */ &ActivateTelemB_Common,
                            /* AppDataFFTxDone */ &AppDataFFTxDone_Common,
                            /* AppDataRequest  */ &AppDataRequest_Mode2,
                            /* AppDataTxFail   */ &AppDataTxFail_Common,
                            /* AutoIDDone      */ &AutoIDDone_Common,
                            /* AutoIDRequest   */ &AutoIDRequest_Mode2,
                            /* CaptureDataDone */ &CaptureDataDone_Common,
                            /* CaptureDataFail */ &CaptureDataFail_Common,
                            /* CloseRequest    */ &CloseRequest_Mode2,
                            /* CloseTxDone     */ &CloseTxDone_Common,
                            /* DataFrameUL     */ &DataFrameUL_Common,
                            /* DeviceIDTx      */ &DeviceIDTx_Common,
                            /* DeviceIDTxDone  */ &DeviceIDTxDone_Mode2,
                            /* EndSession      */ &EndSession_Common,
                            /* FFTxDone        */ &FFTxDone_Common,
                            /* MissedWF        */ &MissedWF_Common,
                            /* OpenDone        */ &OpenDone_Common,
                            /* OpenFail        */ &OpenFail_Common,
                            /* OpenTxDone      */ &OpenTxDone_Mode2,
                            /* RespTimeout     */ &RespTimeout_Common,
                            /* ShortTimeOut    */ &ShortTimeOut_Common,
                            /* TxTimeout       */ &TxTimeout_Mode2,
                            /* UnNumFrameUL    */ &UnNumFrameUL_Common,
                            /* UplinksRequest  */ &UplinksRequest_Mode2,
                            /* WaveformUL      */ &WaveformUL_Common }
};




/**************************************************************
  Definitions for FSM transition functions.
**************************************************************/


static
void
ActivateTelemB_Common(
    struct tbm_Chan* p_fsm)
{
    tbm_tlmAbuse(p_fsm);
}


static
void
ActivateTelemB_Idle(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateMode2;
    tbm_activate(p_fsm);
}


static
void
AppDataFFTxDone_Common(
    struct tbm_Chan* p_fsm)
{
}


static
void
AppDataRequest_Common(
    struct tbm_Chan* p_fsm)
{
    tbm_tlmAbuse(p_fsm);
}


static
void
AppDataRequest_Mode1Hold(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateAwaitOpenResp;
    tbm_listenForOpenResp(p_fsm);
}


static
void
AppDataRequest_Mode2(
    struct tbm_Chan* p_fsm)
{
    tbm_openSession(p_fsm);
}


static
void
AppDataTxFail_Common(
    struct tbm_Chan* p_fsm)
{
}


static
void
AutoIDDone_AwaitDeviceIDResp(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateMode2;
    tbm_autoIDDone(p_fsm);
}


static
void
AutoIDDone_Common(
    struct tbm_Chan* p_fsm)
{
    tbm_unexpTelemEvent(p_fsm);
}


static
void
AutoIDRequest_Common(
    struct tbm_Chan* p_fsm)
{
    tbm_tlmAbuse(p_fsm);
}


static
void
AutoIDRequest_Mode1Hold(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateMode2;
    tbm_tlmAbuse(p_fsm);
    tbm_stopLinkMode1(p_fsm);
}


static
void
AutoIDRequest_Mode2(
    struct tbm_Chan* p_fsm)
{
    tbm_doAutoID(p_fsm);
}


static
void
CaptureDataDone_Common(
    struct tbm_Chan* p_fsm)
{
}


static
void
CaptureDataDone_Mode1(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateMode1Hold;
    tbm_captureDataDone(p_fsm);
}


static
void
CaptureDataFail_Common(
    struct tbm_Chan* p_fsm)
{
}


static
void
CaptureDataFail_Mode1(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateMode2;
    tbm_captureDataDone(p_fsm);
    tbm_stopLinkMode1(p_fsm);
}


static
void
CloseRequest_Common(
    struct tbm_Chan* p_fsm)
{
    tbm_tlmAbuse(p_fsm);
}


static
void
CloseRequest_Mode1Hold(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateClosing;
    tbm_closeSession(p_fsm);
}


static
void
CloseRequest_Mode2(
    struct tbm_Chan* p_fsm)
{
    tbm_doReturn(p_fsm);
}


static
void
CloseTxDone_Closing(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateMode2;
    tbm_stopSession(p_fsm);
    tbm_closeDone(p_fsm);
    tbm_stopLinkMode1(p_fsm);
}


static
void
CloseTxDone_Common(
    struct tbm_Chan* p_fsm)
{
    tbm_unexpTelemEvent(p_fsm);
}


static
void
DataFrameUL_Common(
    struct tbm_Chan* p_fsm)
{
    tbm_FreeFrame(p_fsm);
}


static
void
DataFrameUL_Mode1(
    struct tbm_Chan* p_fsm)
{
    tbm_processULnonWFFrame(p_fsm);
}


static
void
DeviceIDTxDone_Common(
    struct tbm_Chan* p_fsm)
{
    tbm_unexpTelemEvent(p_fsm);
}


static
void
DeviceIDTxDone_Mode2(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateAwaitDeviceIDResp;
    tbm_listenForDeviceIDResp(p_fsm);
}


static
void
DeviceIDTx_AwaitDeviceIDResp(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateMode2;
    tbm_deviceIDTx(p_fsm);
}


static
void
DeviceIDTx_Common(
    struct tbm_Chan* p_fsm)
{
    tbm_unexpTelemEvent(p_fsm);
}


static
void
EndSession_Common(
    struct tbm_Chan* p_fsm)
{
}


static
void
FFTxDone_Common(
    struct tbm_Chan* p_fsm)
{
}


static
void
FFTxDone_Mode1(
    struct tbm_Chan* p_fsm)
{
    tbm_startAppDataTimer(p_fsm);
}


static
void
MissedWF_Common(
    struct tbm_Chan* p_fsm)
{
    tbm_unexpTelemEvent(p_fsm);
}


static
void
MissedWF_Mode1(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateMode1Hold;
    tbm_processMissedWF(p_fsm);
    tbm_captureDataDone(p_fsm);
}


static
void
OpenDone_AwaitOpenResp(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateMode1;
    tbm_initLinkMode1(p_fsm);
}


static
void
OpenDone_Common(
    struct tbm_Chan* p_fsm)
{
}


static
void
OpenFail_AwaitOpenResp(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateMode2;
    tbm_openFail(p_fsm);
}


static
void
OpenFail_Common(
    struct tbm_Chan* p_fsm)
{
}


static
void
OpenTxDone_Common(
    struct tbm_Chan* p_fsm)
{
}


static
void
OpenTxDone_Mode2(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateAwaitOpenResp;
    tbm_listenForOpenResp(p_fsm);
}


static
void
RespTimeout_AwaitDeviceIDResp(
    struct tbm_Chan* p_fsm)
{
    tbm_checkAutoIDDone(p_fsm);
}


static
void
RespTimeout_AwaitOpenResp(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateMode2;
    tbm_openFail(p_fsm);
}


static
void
RespTimeout_Common(
    struct tbm_Chan* p_fsm)
{
    tbm_unexpTelemEvent(p_fsm);
}


static
void
RespTimeout_Mode1(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateMode2;
    tbm_captureDataDone(p_fsm);
    tbm_stopLinkMode1(p_fsm);
}


static
void
ShortTimeOut_AwaitOpenResp(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateMode2;
    tbm_openFail(p_fsm);
}


static
void
ShortTimeOut_Common(
    struct tbm_Chan* p_fsm)
{
}


static
void
ShortTimeOut_Mode1(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateMode2;
    tbm_lossOfTelemetry(p_fsm);
    tbm_captureDataDone(p_fsm);
    tbm_stopLinkMode1(p_fsm);
}


static
void
ShortTimeOut_Mode1Hold(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateMode2;
    tbm_lossOfTelemetry(p_fsm);
    tbm_stopLinkMode1(p_fsm);
}


static
void
TxTimeout_Closing(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateMode2;
    tbm_stopSession(p_fsm);
    tbm_closeDone(p_fsm);
    tbm_stopLinkMode1(p_fsm);
}


static
void
TxTimeout_Common(
    struct tbm_Chan* p_fsm)
{
    tbm_unexpTelemEvent(p_fsm);
}


static
void
TxTimeout_Mode1(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateMode2;
    tbm_txTimeoutMode1(p_fsm);
    tbm_captureDataDone(p_fsm);
    tbm_stopLinkMode1(p_fsm);
}


static
void
TxTimeout_Mode2(
    struct tbm_Chan* p_fsm)
{
    tbm_txTimeoutMode2(p_fsm);
}


static
void
UnNumFrameUL_AwaitDeviceIDResp(
    struct tbm_Chan* p_fsm)
{
    tbm_processDeviceIDResp(p_fsm);
}


static
void
UnNumFrameUL_AwaitOpenResp(
    struct tbm_Chan* p_fsm)
{
    tbm_processOpenResp(p_fsm);
}


static
void
UnNumFrameUL_Common(
    struct tbm_Chan* p_fsm)
{
    tbm_FreeFrame(p_fsm);
}


static
void
UnNumFrameUL_Mode1(
    struct tbm_Chan* p_fsm)
{
    tbm_processULnonWFFrame(p_fsm);
}


static
void
UplinksRequest_AwaitDeviceIDResp(
    struct tbm_Chan* p_fsm)
{
    tbm_tlmAbuse(p_fsm);
}


static
void
UplinksRequest_Common(
    struct tbm_Chan* p_fsm)
{
    tbm_tlmAbuse(p_fsm);
}


static
void
UplinksRequest_Mode1Hold(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateAwaitOpenResp;
    tbm_listenForOpenResp(p_fsm);
}


static
void
UplinksRequest_Mode2(
    struct tbm_Chan* p_fsm)
{
    tbm_openSession(p_fsm);
}


static
void
WaveformUL_AwaitOpenResp(
    struct tbm_Chan* p_fsm)
{
    tbm_processWFOpenResp(p_fsm);
}


static
void
WaveformUL_Common(
    struct tbm_Chan* p_fsm)
{
    tbm_FreeFrame(p_fsm);
}


static
void
WaveformUL_Mode1(
    struct tbm_Chan* p_fsm)
{
    tbm_processULWaveform(p_fsm);
}




/**************************************************************
  Functions for FSM: tbm_Chan
**************************************************************/


void
tbm_Chan_initialize(
    struct tbm_Chan* p_fsm)
{
    p_fsm->p_currentState = &v_stateIdle;
}


const char*
tbm_Chan_stateName(
    struct tbm_Chan* p_fsm)
{
    return p_fsm->p_currentState->name;
}


void
tbm_Chan_ActivateTelemB(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_ActivateTelemB])(p_fsm);
}


void
tbm_Chan_AppDataFFTxDone(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_AppDataFFTxDone])(p_fsm);
}


void
tbm_Chan_AppDataRequest(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_AppDataRequest])(p_fsm);
}


void
tbm_Chan_AppDataTxFail(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_AppDataTxFail])(p_fsm);
}


void
tbm_Chan_AutoIDDone(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_AutoIDDone])(p_fsm);
}


void
tbm_Chan_AutoIDRequest(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_AutoIDRequest])(p_fsm);
}


void
tbm_Chan_CaptureDataDone(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_CaptureDataDone])(p_fsm);
}


void
tbm_Chan_CaptureDataFail(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_CaptureDataFail])(p_fsm);
}


void
tbm_Chan_CloseRequest(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_CloseRequest])(p_fsm);
}


void
tbm_Chan_CloseTxDone(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_CloseTxDone])(p_fsm);
}


void
tbm_Chan_DataFrameUL(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_DataFrameUL])(p_fsm);
}


void
tbm_Chan_DeviceIDTx(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_DeviceIDTx])(p_fsm);
}


void
tbm_Chan_DeviceIDTxDone(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_DeviceIDTxDone])(p_fsm);
}


void
tbm_Chan_EndSession(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_EndSession])(p_fsm);
}


void
tbm_Chan_FFTxDone(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_FFTxDone])(p_fsm);
}


void
tbm_Chan_MissedWF(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_MissedWF])(p_fsm);
}


void
tbm_Chan_OpenDone(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_OpenDone])(p_fsm);
}


void
tbm_Chan_OpenFail(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_OpenFail])(p_fsm);
}


void
tbm_Chan_OpenTxDone(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_OpenTxDone])(p_fsm);
}


void
tbm_Chan_RespTimeout(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_RespTimeout])(p_fsm);
}


void
tbm_Chan_ShortTimeOut(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_ShortTimeOut])(p_fsm);
}


void
tbm_Chan_TxTimeout(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_TxTimeout])(p_fsm);
}


void
tbm_Chan_UnNumFrameUL(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_UnNumFrameUL])(p_fsm);
}


void
tbm_Chan_UplinksRequest(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_UplinksRequest])(p_fsm);
}


void
tbm_Chan_WaveformUL(
    struct tbm_Chan* p_fsm)
{
    (p_fsm->p_currentState->table[c_index_WaveformUL])(p_fsm);
}
