/* Copyright (c) 2002 by Medtronic Inc.  All Rights Reserved */
/********************************************************************
DOCUMENT

$Revision$
$Date$
$RCSfile$

GENERATED FROM FILE:    tbm_fsm.fsm
GENERATED BY:           State Map Compiler (SMC)
                        (version: 3.0)
GENERATED USING SCRIPT: c.sms,v
                        (version: 1.5)
GENERATED ON:           2002-01-15   AT: 10:07:22

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                 !!
!!                          W A R N I N G                          !!
!!                                                                 !!
!!   This file must NOT be changed  manually.  If changes to its   !!
!!   contents are  needed,  the  changes  should  be made to the   !!
!!   corresponding  .fsm file  (identified above) and  the  .h/c   !!
!!   should be regenerated using the SMC tool.                     !!
!!                                                                 !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

ENDDOCUMENT
********************************************************************/


#ifndef tbm_fsm_h
#define tbm_fsm_h




/********************************************************************
DOCUMENT

FINITE STATE MACHINE: tbm_Chan

  This file contains the generated C declarations for
  Finite State Machine (FSM) tbm_Chan.

ENDDOCUMENT
********************************************************************/


struct tbm_Chan_StateObject;


typedef struct tbm_Chan {

    const struct tbm_Chan_StateObject* p_currentState;

} tbm_Chan;

typedef  void (*tbm_Chan_TransitionFunction) (struct tbm_Chan*);

struct tbm_Chan_StateObject {
    const char* name;
    tbm_Chan_TransitionFunction table [25];
};


void          tbm_Chan_initialize (struct tbm_Chan* p_fsm);
const char*   tbm_Chan_stateName  (struct tbm_Chan* p_fsm);

void          tbm_Chan_ActivateTelemB  (struct tbm_Chan* p_fsm);
void          tbm_Chan_AppDataFFTxDone (struct tbm_Chan* p_fsm);
void          tbm_Chan_AppDataRequest  (struct tbm_Chan* p_fsm);
void          tbm_Chan_AppDataTxFail   (struct tbm_Chan* p_fsm);
void          tbm_Chan_AutoIDDone      (struct tbm_Chan* p_fsm);
void          tbm_Chan_AutoIDRequest   (struct tbm_Chan* p_fsm);
void          tbm_Chan_CaptureDataDone (struct tbm_Chan* p_fsm);
void          tbm_Chan_CaptureDataFail (struct tbm_Chan* p_fsm);
void          tbm_Chan_CloseRequest    (struct tbm_Chan* p_fsm);
void          tbm_Chan_CloseTxDone     (struct tbm_Chan* p_fsm);
void          tbm_Chan_DataFrameUL     (struct tbm_Chan* p_fsm);
void          tbm_Chan_DeviceIDTx      (struct tbm_Chan* p_fsm);
void          tbm_Chan_DeviceIDTxDone  (struct tbm_Chan* p_fsm);
void          tbm_Chan_EndSession      (struct tbm_Chan* p_fsm);
void          tbm_Chan_FFTxDone        (struct tbm_Chan* p_fsm);
void          tbm_Chan_MissedWF        (struct tbm_Chan* p_fsm);
void          tbm_Chan_OpenDone        (struct tbm_Chan* p_fsm);
void          tbm_Chan_OpenFail        (struct tbm_Chan* p_fsm);
void          tbm_Chan_OpenTxDone      (struct tbm_Chan* p_fsm);
void          tbm_Chan_RespTimeout     (struct tbm_Chan* p_fsm);
void          tbm_Chan_ShortTimeOut    (struct tbm_Chan* p_fsm);
void          tbm_Chan_TxTimeout       (struct tbm_Chan* p_fsm);
void          tbm_Chan_UnNumFrameUL    (struct tbm_Chan* p_fsm);
void          tbm_Chan_UplinksRequest  (struct tbm_Chan* p_fsm);
void          tbm_Chan_WaveformUL      (struct tbm_Chan* p_fsm);

void          tbm_FreeFrame             (struct tbm_Chan* p_fsm);
void          tbm_activate              (struct tbm_Chan* p_fsm);
void          tbm_autoIDDone            (struct tbm_Chan* p_fsm);
void          tbm_captureDataDone       (struct tbm_Chan* p_fsm);
void          tbm_checkAutoIDDone       (struct tbm_Chan* p_fsm);
void          tbm_closeDone             (struct tbm_Chan* p_fsm);
void          tbm_closeSession          (struct tbm_Chan* p_fsm);
void          tbm_deviceIDTx            (struct tbm_Chan* p_fsm);
void          tbm_doAutoID              (struct tbm_Chan* p_fsm);
void          tbm_doReturn              (struct tbm_Chan* p_fsm);
void          tbm_initLinkMode1         (struct tbm_Chan* p_fsm);
void          tbm_listenForDeviceIDResp (struct tbm_Chan* p_fsm);
void          tbm_listenForOpenResp     (struct tbm_Chan* p_fsm);
void          tbm_lossOfTelemetry       (struct tbm_Chan* p_fsm);
void          tbm_openFail              (struct tbm_Chan* p_fsm);
void          tbm_openSession           (struct tbm_Chan* p_fsm);
void          tbm_processDeviceIDResp   (struct tbm_Chan* p_fsm);
void          tbm_processMissedWF       (struct tbm_Chan* p_fsm);
void          tbm_processOpenResp       (struct tbm_Chan* p_fsm);
void          tbm_processULWaveform     (struct tbm_Chan* p_fsm);
void          tbm_processULnonWFFrame   (struct tbm_Chan* p_fsm);
void          tbm_processWFOpenResp     (struct tbm_Chan* p_fsm);
void          tbm_startAppDataTimer     (struct tbm_Chan* p_fsm);
void          tbm_stopLinkMode1         (struct tbm_Chan* p_fsm);
void          tbm_stopSession           (struct tbm_Chan* p_fsm);
void          tbm_tlmAbuse              (struct tbm_Chan* p_fsm);
void          tbm_txTimeoutMode1        (struct tbm_Chan* p_fsm);
void          tbm_txTimeoutMode2        (struct tbm_Chan* p_fsm);
void          tbm_unexpTelemEvent       (struct tbm_Chan* p_fsm);




#endif /* tbm_fsm_h */
