/* Copyright (c) 2001 by Medtronic Inc.  All Rights Reserved */
/********************************************************************
DOCUMENT

$Revision$
$Date$
$RCSfile$

GENERATED FROM FILE:    tbm_autoid.fsm
GENERATED BY:           State Map Compiler (SMC)
                        (version: 3.0)
GENERATED USING SCRIPT: c.sms,v
                        (version: 1.5)
GENERATED ON:           2001-05-24   AT: 13:20:04

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                 !!
!!                          W A R N I N G                          !!
!!                                                                 !!
!!   This file must NOT be changed  manually.  If changes to its   !!
!!   contents are  needed,  the  changes  should  be made to the   !!
!!   corresponding  .fsm file  (identified above) and  the  .h/c   !!
!!   should be regenerated using the SMC tool.                     !!
!!                                                                 !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

ENDDOCUMENT
********************************************************************/

#include "tbm_autoid.h"

/********************************************************************
DOCUMENT

FINITE STATE MACHINE: tbm_AutoID

  This file contains the generated C implementation for
  Finite State Machine (FSM) tbm_AutoID.

ENDDOCUMENT
********************************************************************/

/**************************************************************
  State object type declaration.
**************************************************************/

typedef void (*tbm_AutoID_TransitionFunction) (struct tbm_AutoID *);

struct tbm_AutoID_StateObject
{
    const char *name;
    tbm_AutoID_TransitionFunction table[2];
};

/**************************************************************
  Declarations for FSM transition functions.
**************************************************************/

static void RespTimeout_AutoID_FSM_Done(struct tbm_AutoID *p_fsm);
static void RespTimeout_Tx0_RxF(struct tbm_AutoID *p_fsm);
static void RespTimeout_Tx2_RxF(struct tbm_AutoID *p_fsm);
static void RespTimeout_Tx2_RxT(struct tbm_AutoID *p_fsm);
static void RespTimeout_Tx3_RxT(struct tbm_AutoID *p_fsm);
static void RespTimeout_Tx4_RxT(struct tbm_AutoID *p_fsm);
static void RespTimeout_Wait1_RxT(struct tbm_AutoID *p_fsm);
static void RespTimeout_Wait2_RxT(struct tbm_AutoID *p_fsm);
static void RespTimeout_Wait3_RxT(struct tbm_AutoID *p_fsm);
static void UniqueRespRx_Common_Wait(struct tbm_AutoID *p_fsm);
static void UniqueRespRx_Tx0_RxF(struct tbm_AutoID *p_fsm);
static void UniqueRespRx_Tx2_RxF(struct tbm_AutoID *p_fsm);
static void UniqueRespRx_Tx2_RxT(struct tbm_AutoID *p_fsm);
static void UniqueRespRx_Tx3_RxT(struct tbm_AutoID *p_fsm);

/**************************************************************
  Transition Indices
**************************************************************/

#define  c_index_RespTimeout  0
#define  c_index_UniqueRespRx 1

/**************************************************************
  State object definitions.
**************************************************************/

static const struct tbm_AutoID_StateObject v_stateAutoID_FSM_Done = {
    "AutoID_FSM_Done",
    { /* RespTimeout  */ &RespTimeout_AutoID_FSM_Done,
                         /*
                            UniqueRespRx
                          */&UniqueRespRx_Common_Wait}
};

static const struct tbm_AutoID_StateObject v_stateTx0_RxF = {
    "Tx0_RxF",
    { /* RespTimeout  */ &RespTimeout_Tx0_RxF,
                         /*
                            UniqueRespRx
                          */&UniqueRespRx_Tx0_RxF}
};

static const struct tbm_AutoID_StateObject v_stateTx2_RxF = {
    "Tx2_RxF",
    { /* RespTimeout  */ &RespTimeout_Tx2_RxF,
                         /*
                            UniqueRespRx
                          */&UniqueRespRx_Tx2_RxF}
};

static const struct tbm_AutoID_StateObject v_stateTx2_RxT = {
    "Tx2_RxT",
    { /* RespTimeout  */ &RespTimeout_Tx2_RxT,
                         /*
                            UniqueRespRx
                          */&UniqueRespRx_Tx2_RxT}
};

static const struct tbm_AutoID_StateObject v_stateTx3_RxT = {
    "Tx3_RxT",
    { /* RespTimeout  */ &RespTimeout_Tx3_RxT,
                         /*
                            UniqueRespRx
                          */&UniqueRespRx_Tx3_RxT}
};

static const struct tbm_AutoID_StateObject v_stateTx4_RxT = {
    "Tx4_RxT",
    { /* RespTimeout  */ &RespTimeout_Tx4_RxT,
                         /*
                            UniqueRespRx
                          */&UniqueRespRx_Common_Wait}
};

static const struct tbm_AutoID_StateObject v_stateWait1_RxT = {
    "Wait1_RxT",
    { /* RespTimeout  */ &RespTimeout_Wait1_RxT,
                         /*
                            UniqueRespRx
                          */&UniqueRespRx_Common_Wait}
};

static const struct tbm_AutoID_StateObject v_stateWait2_RxT = {
    "Wait2_RxT",
    { /* RespTimeout  */ &RespTimeout_Wait2_RxT,
                         /*
                            UniqueRespRx
                          */&UniqueRespRx_Common_Wait}
};

static const struct tbm_AutoID_StateObject v_stateWait3_RxT = {
    "Wait3_RxT",
    { /* RespTimeout  */ &RespTimeout_Wait3_RxT,
                         /*
                            UniqueRespRx
                          */&UniqueRespRx_Common_Wait}
};

/**************************************************************
  Definitions for FSM transition functions.
**************************************************************/

static void RespTimeout_AutoID_FSM_Done(struct tbm_AutoID *p_fsm)
{
}

static void RespTimeout_Tx0_RxF(struct tbm_AutoID *p_fsm)
{
    p_fsm->p_currentState = &v_stateTx2_RxF;
    tbm_continueAutoID(p_fsm);
}

static void RespTimeout_Tx2_RxF(struct tbm_AutoID *p_fsm)
{
    p_fsm->p_currentState = &v_stateAutoID_FSM_Done;
    tbm_concludeAutoID(p_fsm);
}

static void RespTimeout_Tx2_RxT(struct tbm_AutoID *p_fsm)
{
    p_fsm->p_currentState = &v_stateAutoID_FSM_Done;
    tbm_concludeAutoID(p_fsm);
}

static void RespTimeout_Tx3_RxT(struct tbm_AutoID *p_fsm)
{
    p_fsm->p_currentState = &v_stateAutoID_FSM_Done;
    tbm_concludeAutoID(p_fsm);
}

static void RespTimeout_Tx4_RxT(struct tbm_AutoID *p_fsm)
{
    p_fsm->p_currentState = &v_stateAutoID_FSM_Done;
    tbm_concludeAutoID(p_fsm);
}

static void RespTimeout_Wait1_RxT(struct tbm_AutoID *p_fsm)
{
    p_fsm->p_currentState = &v_stateTx2_RxT;
    tbm_continueAutoID(p_fsm);
}

static void RespTimeout_Wait2_RxT(struct tbm_AutoID *p_fsm)
{
    p_fsm->p_currentState = &v_stateTx3_RxT;
    tbm_continueAutoID(p_fsm);
}

static void RespTimeout_Wait3_RxT(struct tbm_AutoID *p_fsm)
{
    p_fsm->p_currentState = &v_stateTx4_RxT;
    tbm_continueAutoID(p_fsm);
}

static void UniqueRespRx_Common_Wait(struct tbm_AutoID *p_fsm)
{
}

static void UniqueRespRx_Tx0_RxF(struct tbm_AutoID *p_fsm)
{
    p_fsm->p_currentState = &v_stateWait1_RxT;
}

static void UniqueRespRx_Tx2_RxF(struct tbm_AutoID *p_fsm)
{
    p_fsm->p_currentState = &v_stateWait2_RxT;
}

static void UniqueRespRx_Tx2_RxT(struct tbm_AutoID *p_fsm)
{
    p_fsm->p_currentState = &v_stateWait2_RxT;
}

static void UniqueRespRx_Tx3_RxT(struct tbm_AutoID *p_fsm)
{
    p_fsm->p_currentState = &v_stateWait3_RxT;
}

/**************************************************************
  Functions for FSM: tbm_AutoID
**************************************************************/

void tbm_AutoID_initialize(struct tbm_AutoID *p_fsm)
{
    p_fsm->p_currentState = &v_stateTx0_RxF;
}

const char *tbm_AutoID_stateName(struct tbm_AutoID *p_fsm)
{
    return p_fsm->p_currentState->name;
}

void tbm_AutoID_RespTimeout(struct tbm_AutoID *p_fsm)
{
    (p_fsm->p_currentState->table[c_index_RespTimeout])(p_fsm);
}

void tbm_AutoID_UniqueRespRx(struct tbm_AutoID *p_fsm)
{
    (p_fsm->p_currentState->table[c_index_UniqueRespRx])(p_fsm);
}
